### ISSUE TITLE
Future Request : Make One Back end Script to check all configured device is accessible using tacacs 

### ISSUE THREAD

**Issue by rajjaisur** [tacacsgui/tacacsgui#11]
Make one back end script which check in every frequency(frequency will be configurable in GUI)
1) which check device is ping able or not
2) if it is then it will check login using tacacs user
3) if it not able to login then it make entry in dashboard( or any other suitable menu/submenu)
4) if device is not ping able don't do any thing 

if you need any help. please ping me on rajjaisur@gmail.com

Thanks
Raj Jaisur

**Comment by gurkin33** [comment]
Hello Raj,
The project in most of all is AAA server and may be after all, I will add some monitoring feature. I have a long list of features that I should add. I will keep in mind your wish.
