### ISSUE TITLE
API authorized false on apply config

### ISSUE THREAD

**Issue by andyb2000** [tacacsgui/tacacsgui#114]
Ubuntu version: 18.04 LTD
PHP version: 7.3.28-1+ubuntu18.04.1+deb.sury.org+1
TacacsGUI API version: 0.9.83
Browser: n/a (curl)

Hi,
I'm applying users via the database direct, and now I have that I want my script to be able to push the "TEST and APPLY" buttons.
I've authenticated using curl like this:
curl --include -H 'Content-Type: application/json' http://localhost:8008/api/auth/signin/ -d '{"username":"autoscript","password":"xxx"}'
Which in the reply gives me my "token"
I can then try to use:

`curl --include -H 'Content-Type: application/json' --header "Authorization: Bearer eyXXX" http://localhost:8008/api/tacacs/config/apply/?contentType=json\&confTest=on\&confSave=yes\&doBackup=0`
(I cut the token down, eyXXX is my valid token)
However I always get back an authorized false error. If I login via the gui for the user autoscript and test+apply it works, so I suspect it's something I'm doing on cli that's at fault.

Here is the output:
`HTTP/1.1 401 Unauthorized
Date: Tue, 03 May 2022 10:46:18 GMT
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: PHPSESSID=a7h2k8r7and9gm1jn14vojohd8; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Access-Control-Allow-Origin: *
Application-name: tacacsgui
Author-Name: Alexey Mochalin
Application-version: 0.9.83
Content-Length: 385
Content-Type: application/json

{"info":{"general":{"type":"get","object":"config","action":"generate to file","time":1651574778},"version":{"TACVER":"201903091339\/PCRE\/LWRES","APIVER":"0.9.83"},"user":{"id":"empty","username":"empty","groupId":"empty","groupRights":"empty","changePasswd":"empty"}},"error":{"status":true,"authorized":false,"message":"You are not authorized"},"authorised":false,"ha_role":"empty"}`

If I pull something like /dashboard, this appears to work and I get output without the 401 unauthorised.
Anyone spot what I'm doing wrong please?

Thank you

**Comment by andyb2000** [comment]
I have solved it.

For anyone else hitting this issue, I forgot to set cookie-jar in curl which is needed.

So the code changes to:

/usr/bin/curl -s --cookie-jar /tmp/authcookie.tmp .... (etc)

Then on subsequent commands:
/usr/bin/curl -s --cookie /tmp/authcookie.tmp ... (etc)

**Comment by shahedfardous** [comment]
@andyb2000 
Thanks a lot for the detailed instruction and also thanks a ton for the updated response with the cookie-jar.
