### ISSUE TITLE
Cisco UCS and Nexus authorization issue - multiple services to a user 

### ISSUE THREAD

**Issue by Dellogeon** [tacacsgui/tacacsgui#117]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
PHP version: PHP 7.3.8-1
TacacsGUI API version: 0.9.83
Browser: Chrome

**Describe the bug**

There are Cisco UCS and Nexus switches in my environment. I created two services for each types of device. As result, only one type of device is working, either UCS or Nexus. They are not working at the same time.

In 'user' configuration, I added both services in the service section.  For example, first service is UCS, then Nexus. As result, UCS authorization is fine, but nexus authorization is not.  Vice versa.

**Comment by gurkin33** [comment]
Hello,

Please use associated services. You can add association with ACL. Based on ACL tacacs will use correct service.
