### ISSUE TITLE
No Authentication Response when we enter wrong credentials on Huawei Devices

### ISSUE THREAD

**Issue by TabishKhalid** [tacacsgui/tacacsgui#119]
When wrong credentials are entered, the password backoff timer of 1 sec is not working on Huawei devices and takes long time and session gets stuck.

in the end we get message that Error: Tacacs authentication has no response.

All other vendor devices  like Juniper and Cisco does not face this issue.

Please help me resolve this.

**Comment by TabishKhalid** [comment]
Basically although Autherntication report shows that Authentication is rejected, We don't recieve any Authentication response message to the Huawei device which results in Tacacs no response error.

Need your kind feedback on this, if any one have any information which can help me.

**Comment by gurkin33** [comment]
I hope you forgot to add link to a solution:
https://groups.google.com/g/event-driven-servers/c/m8ym4DnOA80/m/8PblHGqRAQAJ?utm_medium=email&utm_source=footer
