### ISSUE TITLE
Slow Loading Time

### ISSUE THREAD

**Issue by taxisali** [tacacsgui/tacacsgui#12]
Hi,

i had an issue with very long loading times on an client browser with no internet.
When i opened the GUI, it takes about 2 Minutes to load or change a page.

I out Commented the Google Apis font line in:

> /web/templates/body_start.php

Now, the GUI is loading nice and fast.

Plz be aware, if u use or test tacacsgui in capsualted environments, like tech-labs. 

Have a nice day.

**Comment by gurkin33** [comment]
Hello!
Good comment! Thank you. I will add offline fonts libraries in the next update.

**Comment by gurkin33** [comment]
I have released new version 0.9.28 where I fixed that issue. Thank you and have a nice day!
