### ISSUE TITLE
Possible escaping issue in install script

### ISSUE THREAD

**Issue by QuincyS24** [tacacsgui/tacacsgui#13]
Today I installed TacacsGUI on a new system running Ubuntu Server 16.04.5 LTS.
I followed all the instructions from the documentation on the website.

During the TacacsGUI installation script, there is point where the script will ask you wether you want to use the root password or a custom password for the **tgui_user**.

I found out that when the password contains certain characters they won't be escaped correctly.
In the config.php file located in /opt/tacacsgui/web/api you will see that the DB_PASSWORD string will contain the text **<datatabase_passwd_here>** and a part of the password.

The password I tried to use: **a5!Ak4-i8&Uk2:**

**Comment by gurkin33** [comment]
Hello! 

Thank you for your report. The issue was with char **&**. Now it is escaping while installation process.
