### ISSUE TITLE
Feature Request: Page for users to change password

### ISSUE THREAD

**Issue by rowshi** [tacacsgui/tacacsgui#15]
# Feature Request
It would be nice if there was a page for the TACACS users to use to change their passwords from.

Not the API users, but the TACACS users.

I think this may require a modification to the way the configuration is managed, splitting the users off into a separate file or files.

# Workflow:
1. TACACS user goes to a webpage http://<server>:8008/chpass/
2. Logs in using their current TACACS username and password
3. Given a dialog to change the password (double entry like always)
4. Password is hashed and the configuration is tested then updated automatically (this is why it may be better to split the users off into separate files)

Cheers!

Love the project

**Comment by gurkin33** [comment]
Hello @rowshi 

Now user can change his password via GUI (http://:8008/tac_change_passwd.php) or via device cli (empty password enables that feature).

Best Regards, Aleksey

**Comment by rowshi** [comment]
Looks good!

**Comment by MohammadRamadan** [comment]
Hi,
 First of all thank you so much for this great tool.
and Now I have implemented this server and it's working ok but my problen that this added page of tacacs user to change their passwords is not working. it says error and asks if I am enabled to change password.
my tacgui version is 0.9.83
![tacchagpass](https://user-images.githubusercontent.com/25562327/105673933-6c2cc480-5eef-11eb-96c5-135905de622d.PNG)

**Comment by MohammadRamadan** [comment]
> Hi,
> First of all thank you so much for this great tool.
> and Now I have implemented this server and it's working ok but my problen that this added page of tacacs user to change their passwords is not working. it says error and asks if I am enabled to change password.
> my tacgui version is 0.9.83
> ![tacchagpass](https://user-images.githubusercontent.com/25562327/105673933-6c2cc480-5eef-11eb-96c5-135905de622d.PNG)

Solved, Thank you so much :)

**Comment by sreddi9** [comment]
@MohammadRamadan I'm also facing similar issue, can you tell me how did you solve it?

**Comment by MohammadRamadan** [comment]
Hello, to change the password, simply in the cli you,re trying to login and at step of entering the password in blank just press the ENTER button to change the password.

**Comment by Visdwiz** [comment]
When I press Enter, it just says incorrect password. How to solve it?
