### ISSUE TITLE
Could we install TacacsGUI on CentOS 7?

### ISSUE THREAD

**Issue by samkuonssp** [tacacsgui/tacacsgui#16]
Dear sir/madam,

I am really appreciate for your project which could help network administrator's task more efficiency. Anyway I would like ask/request if we could Install TacacasGUI with CentOS/RedHat 7 or not?

Best regards,
Sam KUON

**Comment by gurkin33** [comment]
Hello Sam,

Could you give me some benefits of Centos? Why I need to do the project with Centos support? Because Centos are not compatible system for my project and if I decide to support Centos I need to create new branch for it.

Best Regards, Aleksey

**Comment by samkuonssp** [comment]
Dear Aleksey,

It is just for education purpose and I believe that CentOS/RHEL is the most
popular for system administrator. So if your project is compatible and
available for distribution linux, system administrator will consider your
software, you maybe get more benefit too.

Thanks & Regards,

*Sam KUON*

*Tel: (855)17 293 696 / (855)86 231 646*
*Email: sam.kuonssp@gmail.com <sam.kuonssp@gmail.com>*


*Address: #49E4, St. 51, Sangkat Phsar Thmey III, Khan Daun Penh, Phnom
Penh, CambodiaSkype: sam.kuonssp*

**Comment by gurkin33** [comment]
Hello @samkuonssp 

Ok. Thank you for information. I will think about it.

Best Regards, Aleksey
