### ISSUE TITLE
LDAP Issue after update

### ISSUE THREAD

**Issue by beepmeep88** [tacacsgui/tacacsgui#17]
Hello,
After the update yesterday, the current LDAP configuration didn't work anymore (just info).

After I made the necessary adjustments, it can now look up AD users again. It doesn't limit access based on our tacacs group anymore though (anyone with correct credentials get ACK). I'm not sure if I'm missing something with group configuration? Should I set this with ACL's now?

Also, when the default user is present in the "users" tab, I get the follwoing error (can be solved by deleting default user, though):

DataTables warning: table id=usersDataTable - Requested unknown parameter 'priv-lvl' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4

Thanks for a great product, will throw a donation your way when I got up and running 👍

**Comment by gurkin33** [comment]
Hello!

Thank you for your feedback. I will try to help.

> After the update yesterday, the current LDAP configuration didn't work anymore (just info).

Yes. Sorry about that. I thought about seamless update, but it is very hard. But new module should work, if you have issues please execute the commands `cd /opt/tacacsgui/; sudo -u www-data git pull origin master; `inside of Ubuntu (root password will require).

> I'm not sure if I'm missing something with group configuration? Should I set this with ACL's now?

New ldap module gets all groups of AD user and does next match:
- if CN of AD group matchs to tacacs user group name , the user is the member of that group;
- if Distinguished Name (DN) of AD group matchs to pre-configured DN inside of a tacacs group , the user is the member of that group.

> Also, when the default user is present in the "users" tab, I get the follwoing error (can be solved by deleting default user, though):

Please try to type **`Ctr + Shift + R`** and give me feedback if it helps.

Best Regards, Aleksey

**Comment by gurkin33** [comment]
And one more answer for:

> Should I set this with ACL's now?

Yes you can set ACL, if you want, they still will be there. But also I added some useful feature with it you can easily allow/restrict access to list of device/device group.

Best Regards, Aleksey

**Comment by beepmeep88** [comment]
Thank you for your quick response. 
In regards to testing the error on the "users" page, I can't do that anymore because I already deleted the default user, which makes the error disappear :)

Thanks for the fallback method, but I got the server working.. For now I only have 1 issue:

How can I make sure that every user authenticating, doesn't get accepted? I've already made a "network-admins" group and added my own user to this. The problem is that everybody else is allowed into the same device.
I tried making another group which should match "domain users" (would catch all) and set an ACL to deny these users, but they don't seem to be matched to this group.

Hope you can help,

Martin

**Comment by beepmeep88** [comment]
Hi Aleksey,

It seems to work as intended now, you can close the issue now 👍 
I'll get back to you if I have any other issues setting this up.

Thanks for the quick fix!

Martin

**Comment by gurkin33** [comment]
Thank you for the feedback.
Have a nice day!

Best Regards, Aleksey
