### ISSUE TITLE
Command-sets

### ISSUE THREAD

**Issue by beepmeep88** [tacacsgui/tacacsgui#18]
Hello Aleksey

I'm sorry to bother you again, but I'm having issues creating command-sets for specific users.

First of all, if I set a priv-lvl for a specific service, it seems like it isn't enforced.. (for example, if I choose priv-lvl 15, I'm not automatically in enable mode on a cisco switch). Could be that I'm missing configuration on the switch though.

When that didn't work, I decided to do command sets and let everybody be priv-lvl 15. however, whenever I set a command, it seems like the "second word" of the command is cleared. (also, if I change action from permit/deny and want to save, the page responds with "no changes detected".

Hope you can help once again :)

Martin

**Comment by gurkin33** [comment]
Hello Martin,

> First of all, if I set a priv-lvl for a specific service, it seems like it isn't enforced.. (for example, if I choose priv-lvl 15, I'm not automatically in enable mode on a cisco switch). Could be that I'm missing configuration on the switch though.

For example. I have AD user and it is a member of CN=CiscoManager. I have a group inside of tacacsgui:
```
    group = 123123 {
    #### LDAP Groups List #### DistinguishedName ###
    ### CN=CiscoManager,OU=Groups,OU=TacacsGUI,DC=win2008,DC=g33 ###
    default service = permit
###Service cisco_max_15 START###
service = shell {
set priv-lvl = 15
default attribute = permit
default cmd = permit
} #END OF Cisco Router/Switch Service
###Service cisco_max_15 END###
  } #END OF 123123
```
When I try to connect I get privilege level 15. Please, check your user groups. Check all groups that applied to your users. To check this, just run test inside of ldap module.

> When that didn't work, I decided to do command sets and let everybody be priv-lvl 15. however, whenever I set a command, it seems like the "second word" of the command is cleared. (also, if I change action from permit/deny and want to save, the page responds with "no changes detected".

I didn't understand what did you mean? I think I need to see that.

Best Regards, Aleksey

**Comment by beepmeep88** [comment]
Hi again,

I checked myself, and you're right.. priv lvls does work.

I've created this user-group that has priv-lvl 7. If I want this group to be able to issue "show running-config" I've done the following configuration:

![image](https://user-images.githubusercontent.com/45483904/49295026-f6667300-f4b4-11e8-815d-6a4c9288b432.png)

Also, I've added this command-set in the Cisco R/S in Services. I've added this service to the user group.

Now, the user can't usually do show running-config with priv-lvl 7, and it still can't with the new configuration.

Disregard my previous sentence.. I was confused by the fact that I didn't think priv-lvls were used.

**Comment by gurkin33** [comment]
I think it is because you just don't have that command as a choice.
```
r_15_dev#sh runn?
% Unrecognized command
```
You need to add that command inside of [privilege level on a device](https://learningnetwork.cisco.com/thread/33142)

Best Regards, Aleksey

**Comment by beepmeep88** [comment]
Okay, I thought I tested that already, but it works now.. 

Thanks and sorry to have wasted your time.

Have a nice weekend
