### ISSUE TITLE
Tacgui 0.9.53 Installation Issue

### ISSUE THREAD

**Issue by satrioyoyo** [tacacsgui/tacacsgui#19]
Hi Tacgui developer!

I'm trying manual installation tacgui 0.9.53. I'm already following the installation guides in https://tacacsgui.com/documentation_old/install-tacacsgui/ ,but failed composer section. there is the log:

`###############################################################
###############################################################

ver. 1.0.0

Start Installation
Check database...
Try to get root password to MySQL...Not Found
Enter root password to mysql:
Done. Correct password
Remember root password? (y/n): n
Test existence of tgui database...Already created
Test existence of tgui_log database...Already created

Check existence of tgui_user.
Already created
It seems like you already have installed version. Do you want to continue? [y/n]: y
Old configuration saved (/tmp/config.php)
Database user password was saved
Check User Grants...Done
Check main directory /opt/tacacsgui ... Already Created
Directory /opt/tacacsgui doesn't empty. Delete all files? (if no, script exit) [y/n]: y
Old configuration saved! (tac_plus.cfg)
Download latest version...
Cloning into '/opt/tacacsgui'...
Cannot create cache directory /home/satrio/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/satrio/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - adldap2/adldap2 v9.1.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2 ^9.1 -> satisfiable by adldap2/adldap2[v9.1.0, v9.1.1, v9.1.2, v9.1.3, v9.1.4].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlrpc.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
    - /etc/php/7.2/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Cannot create cache directory /home/satrio/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/satrio/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - adldap2/adldap2 v9.1.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2 ^9.1 -> satisfiable by adldap2/adldap2[v9.1.0, v9.1.1, v9.1.2, v9.1.3, v9.1.4].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlrpc.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
    - /etc/php/7.2/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Time to create certificate for https support...
Already created.Generate config.php
Restoring old config.php
Preparing apache configuration
Module rewrite already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Module xsendfile already enabled
Site tacacsgui.local already enabled
Site tacacsgui.local-ssl already enabled
Tacacs Daemon setup...
Test Daemon work...Old configuration repaired
Done
Final Check...Check main libraries...
###########    Error!    ###########
Slim Framework not installed!!!
####################################
Press any key to exit...
`

**Comment by gurkin33** [comment]
Hello! 

Please use [new documentation](https://tacacsgui.com/documentation/installation/manual/system-preparation/) to install it manually.

The old documentation will be deprecated soon.

Best Regards, Aleksey
