### ISSUE TITLE
mysql root password on slave server

### ISSUE THREAD

**Issue by coredidan** [tacacsgui/tacacsgui#20]
Добрый день!

При добавлении slave-сервера запрашивает пароль root mysql, но не принимает его. С консоли с тем же паролем пускает.

**Comment by gurkin33** [comment]
Добрый день!

Очень странно, потому что я только что попробовал в тестовой среде и у меня пароль проходит. Возможно используются спец символы? У вас постоянно возвращается окно ввода пароля?

С Уважением, Алексей

**Comment by coredidan** [comment]
Да, окошко все время возвращается, внизу всплывает "Incorrect password". При этом еще странность в Хроме проявляется - он предлагает обновить пароль в своем кэше для пользователя под которым залогинен в tacacsgui, в моем случае это admin, на тот, который введен как пароль root mysql

https://yadi.sk/i/M2o2HJ5ZgIipUQ

**Comment by gurkin33** [comment]
Спасибо за информацию. Подскажите, спецсимволы используете в пароле (любые символы, кроме цифр и букв)?

**Comment by coredidan** [comment]
В пароле для юзера admin (который не для доступа к mysql) - да, есть два воскл знака !!, а пароль рута БД вообще стандартный - tacgui

**Comment by gurkin33** [comment]
Понял. Изучаю проблему.

**Comment by gurkin33** [comment]
Сможете предоставить больше и информации:
- Использовали OVA или устанавливали вручную?
- Какая версия на текущий момент?

**Comment by gurkin33** [comment]
И так, я попробовал. Развернул новый OVA, обновил до последней версии. Попробовал сделать его slave, а мне вылетела ошибка:
> Incorrect PSK or Master IP

Далее я зашел на Master и в поле **List of Slave's ip addresses** вбил адрес slave, применил конфигурацию. Перешел на slave и все получилось. 

Надеюсь это поможет. Либо будем разбираться дальше, что не так.

С Уважением, Алексей

**Comment by coredidan** [comment]
Видимо я что-то начудил - развернул slave из ova заново и все ок, единственное, в файле /var/lib/mysql/auto.cnf пришло сменить server-uuid для запуска репликации mysql

Уточнение по вэб-интерфейсу слэйва - так задумано что на каждой странице всплывает предупреждение?

> Server in Read ONLY mode.
> High Availability role: Slave.
> Status: Active
> Slave_IO_State: Waiting for master to send event

**Comment by gurkin33** [comment]
Добрый день!
Итак,
- Спасибо, что даете обратную связь.
- Подскажите, пожалуйста, что означает фраза "пришлось сменить server-uuid для запуска репликации mysql"? Можно подробнее? Мне не приходилось ничего менять в тестовой среде.
- "Уточнение" было задумано на всех страницах, все верно. Подразумевалось, что слейв будет настроен и забыт, все управление идет через местера, вот почему возникает это "бесящее окно")) чтобы пользователь лишний раз не старался там что-либо сделать. Если Вы не согласны, то я открыт к предложениям.))

С Уважением, Алексей

**Comment by coredidan** [comment]
- реплика mysql не хотела стартовать с таким же server-uuid в конфиге, как и на мастере.
```
root@tacgui:/home/admin# cat /var/lib/mysql/auto.cnf
[auto]
server-uuid=0db394bf-c0a2-11e8-b647-000c2934b82a

```
- c этим все логично, но, имхо, в "бесящем окне" тогда и надпись не помешает типа "Configuration changes allowed only on Master"
