### ISSUE TITLE
Little Web-framework bug

### ISSUE THREAD

**Issue by coredidan** [tacacsgui/tacacsgui#22]
![image](https://user-images.githubusercontent.com/22121810/50391497-f9245300-0756-11e9-8d37-edcf76d60b1f.png)

При нажатии кнопки "Check Update" внизу в списке "List of Slaves" дублируется отображение ведомых серверов

**Comment by gurkin33** [comment]
Добрый день!

Да, есть такое. Вскоре буду переделывать High Availability, поправлю.
Спасибо.

С Уважением, Алексей

**Comment by gurkin33** [comment]
Добрый день!

Насколько я вижу, в версии 0.9.59 проблема решена. Спасибо вам за ваше замечание, если еще что-то найдете, напишите пожалуйста.

С Уважением, Алексей
