### ISSUE TITLE
Authorization issue with LDAP authentication

### ISSUE THREAD

**Issue by bfranche67** [tacacsgui/tacacsgui#25]
I'm using tacacsgui ver. 0.9.58 with LDAP authentication (Microsoft AD) to access Cisco devices.
After logging on with privilege 15 on the device the authorization process works fine for a time period varing from one minute to 3/4 minutes, then it stops working andissuing a command like "sh run" returns an "Command authorization failed"
Here the debug output on the device

![debug](https://user-images.githubusercontent.com/30856689/50887422-655bb380-13f3-11e9-8d2b-5d466f8ce1c3.JPG)

The process starts working again after a succesful authentication process for the same user even on another device, then stops again after the same period of time. It looks as if the tacacs process on the server for some reason forgets the privilege associated with the user after some time.
Using a user stored on the tacacs server the authorization process works fine.
Thanks.

**Comment by gurkin33** [comment]
Hello,

Yes, it is. I fix that, please pull new changes (execute on server) -> `cd /opt/tacacsgui/; sudo -u www-data git pull origin master;`

Hope in helps! Let me know, please.

Best Regards, Aleksey

**Comment by gurkin33** [comment]
And Apply the configuration after pull request! 🔨 

Best Regards, Aleksey

**Comment by bfranche67** [comment]
Hi Aleksey,
it works now but I have another issue, sorry to bother you….
I have two servers configured with HA and I’ve updated both of them without disabling HA; now when I try to logon on the slave sever I got an error probably because the MySQL database is locked and the post upgrade script can not modify it.
I disabled HA on the master now but the problem persists, can you please give me an hint on how to disable HA on the slave via command line ?

Thank you very much.
Bruno



Da: Alexey [mailto:notifications@github.com]
Inviato: mercoledì 9 gennaio 2019 10:16
A: tacacsgui/tacacsgui <tacacsgui@noreply.github.com>
Cc: Franchetti Bruno <franchetti.bruno@creval.it>; Author <author@noreply.github.com>
Oggetto: Re: [tacacsgui/tacacsgui] Authorization issue with LDAP authentication (#25)


And Apply the configuration after pull request! 🔨

Best Regards, Aleksey

**Comment by gurkin33** [comment]
Hello Bruno,

Does it not work on slave server?

![image](https://user-images.githubusercontent.com/19661272/50890841-06eeff00-140c-11e9-8558-c48f389d613b.png)

Best Regards, Aleksey

**Comment by bfranche67** [comment]
Yes, when I try to logon on the slave server after the upgrade I got this error:

![image](https://user-images.githubusercontent.com/30856689/50891195-0babb700-13fc-11e9-84b3-79180e9d06e7.png)

**Comment by gurkin33** [comment]
Looks bad.
Try that on slave server -> `sudo -u www-data bash -c "echo '[]' > /opt/tgui_data/ha/ha.cfg"`

Best Regards, Aleksey

**Comment by bfranche67** [comment]
Ok, now the slave works, no more HA configured.
One last issue:
when I connect to the ex master tha dashboard doesn't work

![image](https://user-images.githubusercontent.com/30856689/50893857-2719c080-1402-11e9-875c-e18a8c747f0f.png)

while it works fine on the ex slave:

![image](https://user-images.githubusercontent.com/30856689/50893894-43b5f880-1402-11e9-9de3-e027585eafe0.png)

Thanks.

**Comment by gurkin33** [comment]
Your browser cached the page. Use combination of `Ctrl + Shift + R`. ☕️

**Comment by bfranche67** [comment]
Ooops...
Thank you very much, you are doing a great work.

Best regards.
Bruno

**Comment by gurkin33** [comment]
Hello Bruno,

Could you update to version 0.9.59 and let me know if that fix your issue and High Availability work good?

Best Regards, Aleksey

**Comment by bfranche67** [comment]
Hello Aleksey,
I did the update and everthing is working.

Thank you very much.

King regards,
Bruno



Da: Alexey [mailto:notifications@github.com]
Inviato: domenica 20 gennaio 2019 09:09
A: tacacsgui/tacacsgui <tacacsgui@noreply.github.com>
Cc: Franchetti Bruno <franchetti.bruno@creval.it>; Author <author@noreply.github.com>
Oggetto: Re: [tacacsgui/tacacsgui] Authorization issue with LDAP authentication (#25)


Hello Bruno,

Could you update to version 0.9.59 and let me know if that fix your issue and High Availability work good?

Best Regards, Aleksey

**Comment by gurkin33** [comment]
Hello Bruno,

Nice to hear. Have a nice day!
Ticket closed.

Best Regards, Aleksey
