### ISSUE TITLE
Web interface crash on Slave

### ISSUE THREAD

**Issue by Izanatos** [tacacsgui/tacacsgui#27]
Hi,

First of all this is a great project and I salute your work. 👍 

Using the OVA I've setup a Failover Master/Slave but when I login on the slave I am getting  :
![tacgui_slave_bug](https://user-images.githubusercontent.com/46830654/51417937-75545f80-1b78-11e9-8d81-95da40c9094c.png)

Also find attached the full output.

Any idea?

regards,
[tacgui_gui_bug_slave_output.txt](https://github.com/tacacsgui/tacacsgui/files/2774845/tacgui_gui_bug_slave_output.txt)

**Comment by gurkin33** [comment]
Hello,

Sorry about that. I have a plan to release new version on Monday (21.01.2019), where the issue will fixed, but re-installation process will required.
 
Best Regards, Aleksey

**Comment by Izanatos** [comment]
Hi Aleksey,

Thanks for the update !  Keep up the good work.

**Comment by gurkin33** [comment]
Hello!

Could you update to version 0.9.59 and let me know if that fix your issue?

Best Regards, Aleksey

**Comment by Izanatos** [comment]
Hi,

running 0.9.59 now on both servers but same issue.

![tacgui_slave_bug_v0 9 59](https://user-images.githubusercontent.com/46830654/51443050-94b7cd80-1cdb-11e9-9f50-727acb90c053.png)

(screenshot attached above is just after update and setting up HA)

I just restarted the server and I only getting a "Loading..." message. (tried CTRL+SHIFT R and a reboot but same behaviour)

regards,

A

**Comment by gurkin33** [comment]
Ok. Looks bad. Did you re-install it or made a pull request? Last version require re-installation -> https://tacacsgui.com/documentation_old/system-reinstallation/

**Comment by Izanatos** [comment]
I did  a re-installation following the process you describe in the link you shared.

**Comment by gurkin33** [comment]
Ok. Let try to find out. Could you save the page with error (Ctrl + S) and send on my email? 
developer@tacacsgui.com

Best Regards, Aleksey

**Comment by Izanatos** [comment]
unfortunatly after the reboot I am getting stuck at the loading screen.

in syslog I am getting : 

Jan 20 20:39:51 tacacs2 mysqld[1181]: 2019-01-20T19:39:51.599216Z 10 [Note] Access denied for user 'tgui_ro'@'localhost' (using password: YES)
Jan 20 20:39:52 tacacs2 mysqld[1181]: 2019-01-20T19:39:52.016745Z 11 [Note] Access denied for user 'tgui_ro'@'localhost' (using password: YES)
Jan 20 20:39:52 tacacs2 mysqld[1181]: 2019-01-20T19:39:52.321695Z 12 [Note] Access denied for user 'tgui_ro'@'localhost' (using password: YES)
Jan 20 20:39:52 tacacs2 mysqld[1181]: 2019-01-20T19:39:52.596713Z 13 [Note] Access denied for user 'tgui_ro'@'localhost' (using password: YES)

**Comment by gurkin33** [comment]
Could you run this one: `sudo rm /opt/tgui_data/ha/ha.*`?

**Comment by Izanatos** [comment]
That's brought the interface backup.

I can try to re-cluster the pair but something tells me it'll crash again

**Comment by gurkin33** [comment]
Let try one more time create master and slave. Let me know if the same error will appear.

**Comment by Izanatos** [comment]
Looking good know 👍 
getting the HA pop - up : 
Server in Read ONLY mode.
High Availability role: Slave.
Status: Active
Slave_IO_State: Waiting for master to send event.

So if we add the rm /opt/tgui_data/ha/ha.* to the reinstall that would be a good tips.

BTW amazing support m8 :)

**Comment by gurkin33** [comment]
Phew! Could we close the ticket? 

Best Regards, Aleksey

**Comment by Izanatos** [comment]
We indeed ! great stuff
