### ISSUE TITLE
How to upgrade tacgui?

### ISSUE THREAD

**Issue by exinyu** [tacacsgui/tacacsgui#28]
What is the password of OVF root? How to upgrade tacgui?

**Comment by gurkin33** [comment]
Hello,

OVA root password (mysql, shell) is *tacgui*. [Here is more info](https://tacacsgui.com/download/).

To upgrade OVA please follow [this instruction](https://tacacsgui.com/documentation_old/system-reinstallation/).

Best Regards, Aleksey

**Comment by exinyu** [comment]
Hello,
I tried many times and couldn't upgrade.

**Comment by gurkin33** [comment]
Oh. Ok.

Please run:
`sudo apt-get update`
`sudo apt-get full-upgrade -y`
And try again.

Does you use proxy or firewall?

**Comment by exinyu** [comment]
tacgui@tacgui:~$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK

**Comment by gurkin33** [comment]
Let try to update from official repo:

#### Uninstall Composer:
```
sudo apt-get remove composer
```
#### Download and Install from official repo:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```
#### Make it as Global:
```
sudo mv composer.phar /usr/bin/composer
```
After that you should have new version of composer
```
composer -V
Composer version 1.8.0 2018-12-03 10:31:16
```
And try to make update of tacacsgui one more time. :monkey:

**Comment by exinyu** [comment]
tacgui@tacgui:~/tacgui$ sudo apt-get remove composer
[sudo] password for tacgui: 
Sorry, try again.
[sudo] password for tacgui: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  javascript-common jsonlint libjs-excanvas mercurial mercurial-common php-cli-prompt php-composer-semver
  php-composer-spdx-licenses php-json-schema php-symfony-console php-symfony-filesystem php-symfony-finder
  php-symfony-process
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  composer
0 upgraded, 0 newly installed, 1 to remove and 131 not upgraded.
After this operation, 1,657 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 74936 files and directories currently installed.)
Removing composer (1.0.0~beta2-1) ...
Processing triggers for man-db (2.7.5-1) ...
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
tacgui@tacgui:~/tacgui$ ll
total 284
drwxrwxr-x 5 tacgui tacgui   4096 Jan 29 16:06 ./
drwxr-xr-x 7 tacgui tacgui   4096 Jan 29 15:21 ../
-rw-rw-r-- 1 tacgui tacgui 263621 Jan 29 16:06 composer-setup.php
drwxrwxr-x 4 tacgui tacgui   4096 Aug  2 13:15 inc/
drwxrwxr-x 2 tacgui tacgui   4096 Jul 31 22:38 log/
-rwxr-xr-x 1 tacgui tacgui   2598 Aug  2 19:13 tacacsgui.sh*
drwxrwxr-x 2 tacgui tacgui   4096 Aug  3 16:25 tmp/
tacgui@tacgui:~/tacgui$ php composer-setup.php
All settings correct for using Composer
Downloading...

Composer (version 1.8.0) successfully installed to: /home/tacgui/tacgui/composer.phar
Use it: php composer.phar

tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ php -r "unlink('composer-setup.php');"
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ sudo mv composer.phar /usr/bin/composer
tacgui@tacgui:~/tacgui$ composer -V
Composer version 1.8.0 2018-12-03 10:31:16
tacgui@tacgui:~/tacgui$ 
tacgui@tacgui:~/tacgui$ sudo ./tacacsgui.sh 
[sudo] password for tacgui: 

###############################################################
##############   TACACSGUI Installation Script    ##############
###############################################################

ver. 1.0.0

##############     List of available options    ##############

1) Install TacacsGUI       5) Clear and Refresh Menu
2) Re-install TacacsGUI    6) Write to Log file
3) Network Settings        7) Quit
4) Test the System

Please enter your choice (5 to clear output): 2

### Re-install TacacsGUI ###


### Test the System ###

Done.  ### Network Settings Check was Completed Successfully  ###

Done.  ### GitHub Available  ###

Done.  ### Composer Repo Available  ###

Done.  ### Tacacs Daemon Installed  ###

Done.  ### PHP 7.2 Installed  ###

Done.  ### Correct version of Ubuntu Installed  ###


###############################################################
##############   TACACSGUI Installation    #########
###############################################################

ver. 1.0.0


Start Installation
Check database...
Try to get root password to MySQL...Verify...Success
Test existence of tgui database...Already created
Test existence of tgui_log database...Already created

###############################################
  Caution! Attention!
  The passwords of DB Users
  will be stored in clear text inside
  /opt/tacacsgui/web/api/config.php
###############################################

Check existence of tgui_user. 
Already created
It seems like you already have installed version. Do you want to continue? [y/n]: y
Old configuration saved (/tmp/config.php)
Database user password was saved
Check User Grants...Done
Check main directory /opt/tacacsgui ... Already Created
Directory /opt/tacacsgui doesn't empty. Delete all files? (if no, script exit) [y/n]: y
Old configuration saved! (tac_plus.cfg)
Download latest version...
Cloning into '/opt/tacacsgui'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 7203 (delta 135), reused 172 (delta 70), pack-reused 6919
Receiving objects: 100% (7203/7203), 10.28 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (3062/3062), done.
Checking connectivity... done.

                                                                                
  [RuntimeException]                                                            
  Invalid working directory specified, =/opt/tacacsgui/web/api does not exist.  
                                                                                


                                                                                
  [RuntimeException]                                                            
  Invalid working directory specified, =/opt/tacacsgui/web/api does not exist.  
                                                                                

Time to create certificate for https support...
Already created.Generate config.php
Restoring old config.php
Preparing apache configuration
Module rewrite already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Module xsendfile already enabled
Site tacacsgui.local already enabled
Site tacacsgui.local-ssl already enabled
Tacacs Daemon setup...
Test Daemon work...Old configuration repaired
Done
Final Check...Check main libraries...
###########    Error!    ###########
Slim Framework not installed!!!
####################################

**Comment by gurkin33** [comment]
Wow.

I have just do the same thing and it was work for me. Don't worry, we will resolve it.

Could you give me output of:
`ls -l /opt/tacacsgui/`
`ls -l /opt/tacacsgui/web/api`
`sudo -u  www-data composer install -d=/opt/tacacsgui/web/api`

**Comment by gurkin33** [comment]
I have found an issue. Give me a moment I will fix installation script.

**Comment by exinyu** [comment]
tacgui@tacgui:~/tacgui$ ls -l /opt/tacacsgui/
total 100
-rwxrwxr-- 1 www-data www-data  6330 Jan 29 16:32 backup.sh
-rwxr-xr-x 1 www-data www-data  9284 Jan 29 16:32 interfaces.sh
-rw-r--r-- 1 www-data www-data 35128 Jan 29 16:32 LICENSE
-rwxrwxr-- 1 www-data www-data  3516 Jan 29 16:32 main.sh
drwxr-xr-x 5 www-data www-data  4096 Jan 29 16:32 mavis
drwxr-xr-x 3 www-data www-data  4096 Jan 29 16:32 parser
-rw-r--r-- 1 www-data www-data   176 Jan 29 16:32 README.md
-rw-r--r-- 1 www-data www-data  9047 Jan 29 16:32 Release_changes.txt
drwxr-xr-x 4 www-data www-data  4096 Jan 29 16:32 scripts
-rw-rw-rw- 1 www-data www-data     0 Jan 29 16:32 tac_plus.cfg
-rw-rw-rw- 1 www-data www-data     0 Jan 29 16:32 tac_plus.cfg_test
-rwxrwxr-- 1 www-data www-data  2315 Jan 29 16:32 tac_plus.sh
-rw-rw-rw- 1 www-data www-data     0 Jan 29 16:32 tacTestOutput.txt
drwxr-xr-x 2 www-data www-data  4096 Jan 29 16:32 temp
drwxr-xr-x 7 www-data www-data  4096 Jan 29 16:32 web
tacgui@tacgui:~/tacgui$ ls -l /opt/tacacsgui/web/api
total 28
drwxr-xr-x 9 www-data www-data 4096 Jan 29 16:32 app
drwxr-xr-x 2 www-data www-data 4096 Jan 29 16:32 bootstrap
-rw-r--r-- 1 www-data www-data  684 Jan 29 16:32 composer.json
-rw-r--r-- 1 www-data www-data 1070 Jan 29 16:32 config_example.php
-rw-r--r-- 1 root     root     1073 Jan 29 16:32 config.php
-rw-r--r-- 1 www-data www-data  365 Jan 29 16:32 constants.php
-rw-r--r-- 1 www-data www-data   61 Jan 29 16:32 index.php
tacgui@tacgui:~/tacgui$ sudo -u www-data composer install -d=/opt/tacacsgui/web/api

                                                                                
  [RuntimeException]                                                            
  Invalid working directory specified, =/opt/tacacsgui/web/api does not exist.

**Comment by gurkin33** [comment]
I've fixed installation script. Please try that:

```
cd ~ ; rm ~/tacgui.tar.gz*
wget https://tacacsgui.com/downloads/tacgui.tar.gz --no-check-certificate
sudo rm -r ~/tacgui; tar -xvf tacgui.tar.gz -C ~; sudo chmod 755 ~/tacgui/tacacsgui.sh
cd ~/tacgui; sudo ./tacacsgui.sh;
```

Hope it will help. Please let me know the result.

**Comment by exinyu** [comment]
tacgui@tacgui:~/tacgui$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.0
PHP version: 7.2.9
PHP binary path: /usr/bin/php7.2

**Comment by gurkin33** [comment]
Ok. You forget to do that:
```
sudo apt-get install -y make gcc composer openssl curl php-curl php-mcrypt php-mbstring php-gettext zip unzip libnet-ldap-perl ldap-utils ntp libapache2-mod-xsendfile php7.2 php7.2-common php7.2-cli php7.2-fpm php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml libapache2-mod-php7.2 php7.2-ldap
```
Do that and try to reinstall again.

**Comment by exinyu** [comment]
The upgrade is complete. Thank you very much.

**Comment by exinyu** [comment]
but the root user's password is not tacgui. so i can't reboot system with tacgui

tacgui@tacgui:~/PROJECTS$ su - root
Password: 
su: Authentication failure
tacgui@tacgui:~/PROJECTS$ reboot
Failed to set wall message, ignoring: Interactive authentication required.
Failed to reboot system via logind: Interactive authentication required.
Failed to start reboot.target: Interactive authentication required.
See system logs and 'systemctl status reboot.target' for details.
Failed to open /dev/initctl: Permission denied
Failed to talk to init daemon.

**Comment by exinyu** [comment]
sorry，i got it

sudo -s

**Comment by gurkin33** [comment]
To reboot the system please use the follow cmd:
`sudo shutdown -r now`

**Comment by exinyu** [comment]
can't add tacacs user and user groups

**Comment by gurkin33** [comment]
I can't recreate the issue. In any way tacacs device group is successfully creating.

Could you use the combination of `Ctrl + Shift + R` to clear browser cache on pages with errors?

If error will repeat, please create new issue (ticket) with full description. It is enough for this ticket. Thanks.

Best Regards, Aleksey

**Comment by enoch85** [comment]
Just came here since the API wasn't the latest, and manage to update with these instructions and a bit of bash skills.

Just a question, is this still maintained considering that the last update was years ago?
