### ISSUE TITLE
Unable to complete install due to network interface not being found

### ISSUE THREAD

**Issue by manofcolombia** [tacacsgui/tacacsgui#29]
**Describe the system**
Ubuntu version: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

PHP version: 
PHP 7.2.15-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:37:29) ( NTS )

TacacsGUI API version: N/A, not installed yet

**Describe the bug**
Unable to complete install documentations because the network interfaces listed in the script are found, but when the script tries to edit/view configuration an error occurs.

**To Reproduce**
1. Launch the tacacsgui.sh with root perms
2. Try to install, install fails - see network section
3. See network section, attempt to configure
4. Error occurs

**Screenshots**
###############################################################
###############################################################

ver. 1.0.0

##############     List of available options    ##############

1) Show Interface List      4) Clear and Refresh Menu
2) Show Interface Settings  5) Back to Main Menu
3) Configure interface

Please enter your choice (4 to clear output): 1

### Show Interface List ###

lo
enp1s0

Please enter your choice (4 to clear output): 2

### Show Interface Settings ###

Type the name of interface: enp1s0
###########    Error!    ###########
Unrecognized Interface
####################################

Please enter your choice (4 to clear output): 3

Type the name of interface: enp1s0
###########    Error!    ###########
Unrecognized Interface enp1s0
####################################

Please enter your choice (4 to clear output): 

**Additional context**

**Comment by manofcolombia** [comment]
I followed the old documentation. 
Follow the new documentation all over again from and it works https://tacacsgui.com/documentation/installation/manual/system-preparation/

**Comment by gurkin33** [comment]
Hello,

Thank you for you request and response. 👍  I want to improve documentation 🛠, could you tell me how did you got the old documentation page? Was it google search or direct link?  
Looking forward for your answer.

Best Regards, Aleksey

**Comment by Cipitaa** [comment]
I can´t see the new documentation, the page show me 404 page not found and I have the same problem with the network interface, could you tell me the steps to solve it?

**Comment by gurkin33** [comment]
Hello,

Could you give me a link or screenshot? Please give more information - wha are you looking for, what do you click or type? It will be good if you start from the beginning of your story.

Regards, Aleksey

**Comment by gurkin33** [comment]
Sorry, now I got you.

New link here -> https://tacacsgui.com/documentation/installation/ova/change-ip-address/

Regards, Aleksey

**Comment by Cipitaa** [comment]
Well, I have the same problem than @manofcolombia I'm tryingto install TACACS in linux but I'm unable to complete install due to network interface not being found. @manofcolombia shared a link where we can see the new documentation but it shows me 404 Page Not Found.

**Comment by Cipitaa** [comment]
Thank you so much @gurkin33
