### ISSUE TITLE
I can't install.

### ISSUE THREAD

**Issue by framirezu** [tacacsgui/tacacsgui#3]
Hi.
I just installed tacacsgui according to the following manual: https://tacacsgui.com/docs.php

But I could not make it work.

1. After finishing the execution of the installation script ("Done. Congratulation!")
I see that you have created the database, but without structure.
2. When I try to start a session, it does not enter and the following error appears: (500 Interval Server error). But I suppose it must be because of the empty database error.

I have tried to search the database structure on your github to try to create it manually, but I have not found it.

In advance, thanks for your feedback.

Very good project.

**Comment by gurkin33** [comment]
Hello!

Thank you for interesting to the project.

First of all, api creates database after first login. I will try to help you. Could you put here the last few log entries, please use that command -> `tail -f /opt/tacacsgui/log/apache2/error.log`. And I think you forgot to do something from the list of my docs :)

Best Regards, Alexey

**Comment by framirezu** [comment]
Hi.

Thanks for you reply.

When I try to enter the web the image remains frozen and the following error appears in the debug.
![image](https://user-images.githubusercontent.com/7587637/38880976-9599472c-422c-11e8-87ae-ddc9b176e5e4.png)

No additional line appears in the error log, only errors appear when the service starts.

```
[Tue Apr 17 10:43:10.961610 2018] [ssl:warn] [pid 1387] AH01906: tacacsgui.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Apr 17 10:43:10.962391 2018] [ssl:warn] [pid 1387] AH01909: tacacsgui.local:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 17 10:43:11.053454 2018] [ssl:warn] [pid 1402] AH01906: tacacsgui.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Apr 17 10:43:11.053499 2018] [ssl:warn] [pid 1402] AH01909: tacacsgui.local:443:0 server certificate does NOT include an ID which matches the server name
```

I noticed that the tacacs service is not active. And when I try to start it manually I get the following error:

```
root@lnoc-tacacsgui:~# /opt/tacacsgui/tac_plus.sh start
2002: /opt/tacacsgui/tac_plus.cfg:1: FATAL: No configuration for id 'spawnd' found.
********************************************************************************
* Unable to start tac_plus ... please fix the configuration problem
* indicated above.
********************************************************************************

```

I hope this is enough information.


Best regards.

**Comment by gurkin33** [comment]
Hello you are a really good debugger. Lol. 
Could you expand message "Slim Application error" in your browser?  And I think the better way is to reinstall your tacacsgui application and give more attention when you will follow the doc.
And also important question - Did you use Ubuntu 16.04.4? Did you install php v.7.2?
I'll try to make a new copy of my application today and I will follow the doc on the main site.

But even so, could you give me information from Slim Application error message? Thanks.

**Comment by gurkin33** [comment]
I have made new copy of application, I just followed the doc and it is work for me... Please, share your experience here.

**Comment by gurkin33** [comment]
Hello!
Glad to hear that you successfully installed that application. I will close that issue.

Best Regards, Aleksey

**Comment by mmihir82** [comment]
I'm getting the same error, what is the solution?
