### ISSUE TITLE
Slim Framework not installed!!!

### ISSUE THREAD

**Issue by Izanatos** [tacacsgui/tacacsgui#32]
Hi,

I tried to install the new update but as at the end of the script I got :

Final Check...Check main libraries...
###########    Error!    ###########
Slim Framework not installed!!!
####################################

now the interface is not loading.

any idea ?

thanks,

A

**Comment by gurkin33** [comment]
Hello,

Did you do setup or re-install the system?
May be I know where is an issue, could you do that:
```
sudo apt-get remove composer -y
```
And then try to re-install.

Please let me know if it resolve your issue.

Best Regards, Aleksey

**Comment by Izanatos** [comment]
Hi,

I did 
administrator@server:~/tgui_install$ sudo apt-get remove composer -y
[sudo] password for administrator:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'composer' is not installed, so not removed
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
administrator@m2matacsrv01:~/tgui_install$

but I still get the same error.

what would be helpful to for to troubleshot this?

thanks,

A

**Comment by gurkin33** [comment]
Could you give me output of `composer -V`?

Best Regards, Aleksey

**Comment by Izanatos** [comment]
Composer version 1.8.4 2019-02-11 10:52:10

**Comment by gurkin33** [comment]
When you try to install what does the log write after the lines:
```
...
###############################################
    Caution! Attention!
    The passwords of DB Users
    will be stored in clear text inside
    /opt/tacacsgui/web/api/config.php
  ###############################################
  
  Check existence of tgui_user. 
  Already created
  It seems like you already have installed version. Do you want to continue? [y/n]: y
  Old configuration saved (/tmp/config.php)
  Database user password was saved
  Check User Grants...Done
  Check main directory /opt/tacacsgui ... Already Created
  Directory /opt/tacacsgui doesn't empty. Delete all files? (if no, script exit) [y/n]: y
  Old configuration saved! (tac_plus.cfg)
  Download latest version...
  Cloning into '/opt/tacacsgui'...
  remote: Enumerating objects: 527, done.
  remote: Counting objects: 100% (527/527), done.
  remote: Compressing objects: 100% (245/245), done.
  remote: Total 7446 (delta 246), reused 506 (delta 237), pack-reused 6919
  Receiving objects: 100% (7446/7446), 10.41 MiB | 2.99 MiB/s, done.
  Resolving deltas: 100% (3173/3173), done.
  Checking connectivity... done.
```
Composer start to work:
```
  Cannot create cache directory /home/tacgui/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
  Cannot create cache directory /home/tacgui/.composer/cache/files/, or directory is not writable. Proceeding without cache
  Loading composer repositories with package information
  Updating dependencies (including require-dev)
  Package operations: 44 installs, 0 updates, 0 removals
    - Installing php-smpp/php-smpp (1.2): Downloading (100%)         
    - Installing psr/container (1.0.0): Downloading (100%)         
    - Installing container-interop/container-interop (1.2.0): Downloading (100%)         
    - Installing nikic/fast-route (v1.3.0): Downloading (100%)         
    - Installing psr/http-message (1.0.1): Downloading (100%)    
...
```
It is a part where composer start to work.
Do you see the same?

**Comment by Izanatos** [comment]
you are right that is the issue : 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - adldap2/adldap2 v9.1.4 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.3 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.2 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v9.1.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2 ^9.1 -> satisfiable by adldap2/adldap2[v9.1.0, v9.1.1, v9.1.2, v9.1.3, v9.1.4].

I did sudo apt-get install -y php7.3-ldap and it worked all installed fine :)

**Comment by Izanatos** [comment]
Thanks for your great support as always 😊
