### ISSUE TITLE
Console authentication

### ISSUE THREAD

**Issue by beepmeep88** [tacacsgui/tacacsgui#34]
**Describe the system**
Ubuntu version: 16.04.5 LTS
(use next command: lsb_release -a )
PHP version: 7.3.3
(use next command: php -v )
TacacsGUI API version: 0.9.61
Browser: Chrome

**Describe the bug**
SSH authentication works fine, when I try to authenticate through the console port, I get the following error from tac_plus:
shell login for 'myusername' from async on tty0 denied by ACL

the "tacacs reports -> authentication" writes:
localhost | 10.1.20.244 | myusername | async | shell login denied by ACL

I don't have any ACL's configured, I'm wondering if it could be because the NAC IP is listed as 'async'?

When I debug on the switch, I'm not getting the usual FAIL, it returns with GET_PASS:

**When console prompt is opened:**
1d06h: AAA: parse name=tty0 idb type=-1 tty=-1
1d06h: AAA: name=tty0 flags=0x11 type=4 shelf=0 slot=0 adapter=0 port=0 channel=0
1d06h: AAA/MEMORY: create_user (0x80D7F8C4) user='' ruser='' port='tty0' rem_addr='async' authen_type=ASCII service=LOGIN priv=1
1d06h: AAA/AUTHEN/START (266336179): port='tty0' list='TACACS_LOGIN' action=LOGIN service=LOGIN
1d06h: AAA/AUTHEN/START (266336179): found list TACACS_LOGIN
1d06h: AAA/AUTHEN/START (266336179): Method=tacacs+ (tacacs+)
1d06h: TAC+: send AUTHEN/START packet ver=192 id=266336179
1d06h: TAC+: ver=192 id=266336179 received AUTHEN status = GETUSER
1d06h: AAA/AUTHEN (266336179): status = GETUSER

**When username is entered:**
1d06h: AAA/AUTHEN/CONT (266336179): continue_login (user='')
1d06h: AAA/AUTHEN (266336179): status = GETUSER
1d06h: AAA/AUTHEN (266336179): Method=tacacs+ (tacacs+)
1d06h: TAC+: send AUTHEN/CONT packet id=266336179
1d06h: TAC+: ver=192 id=266336179 received AUTHEN status = GETPASS
1d06h: AAA/AUTHEN (266336179): status = GETPASS

**When password is entered:**
1d06h: AAA/AUTHEN/CONT (266336179): continue_login (user='myusername')
1d06h: AAA/AUTHEN (266336179): status = GETPASS
1d06h: AAA/AUTHEN (266336179): Method=tacacs+ (tacacs+)
1d06h: TAC+: send AUTHEN/CONT packet id=266336179
1d06h: TAC+: ver=192 id=266336179 received AUTHEN status = GETPASS
1d06h: AAA/AUTHEN (266336179): status = GETPASS

I hope it's a mistake that I made, but I've checked the switch configuration several times.

I've tested this with 2 different Cisco switches.

**Comment by gurkin33** [comment]
Hello,

I just have tried and got success.

**My User Settings:**
```
  user = admin3 {
    login = clear "123123"
    pap = login # Clone login
    enable = login # Clone login
    default service = permit
    ###Service cisco_max_15 START###
    service = shell {
      set priv-lvl = 1
      default attribute = permit
      default cmd = permit
    } #END OF Cisco Router/Switch Service
    ###Service cisco_max_15 END###
  } #END OF admin3
```
**Authe log**:
admin3 | async | shell login succeeded

2019-03-15 17:10:36 | localhost | 1.1.1.1 | admin3 | async | enable 15 succeeded
2019-03-15 17:10:32 | localhost | 1.1.1.1 | admin3 | async | shell login succeeded

**Cisco Router**
```
aaa authentication login tacGUI group tacacs+ local
aaa authentication enable default group tacacs+ enable
!...
line con 0
 logging synchronous
 login authentication tacGUI
```
Hope it will help.

Best Regards, Aleksey

**Comment by beepmeep88** [comment]
Thanks for your reply.

That is weird - the only place your configuration deviates from mine is authorization commands, but that shouldn't prevent authentication.

`aaa authentication login TACACS_LOGIN group tacacs+ local
aaa authorization exec TACACS_EXEC group tacacs+ local

line con 0
 authorization exec TACACS_EXEC
 logging synchronous
 login authentication TACACS_LOGIN
`

Do you have any chance of testing this with LDAP integration? My LDAP group is configured like this:

`
group = network-admins {
    #### LDAP Groups List #### DistinguishedName ###
    ### CN=net-admins,OU=10 TEST,OU=USER,OU=TEST,DC=bll,DC=COM ###
    enable = crypt $¤#1X2V\st2szkogmt35dd2X.
    message = "You've been authenticated and you're authorized to use privilege level 15 (FULL ACCESS!)"
    acl = Permit-all
    default service = permit
    ###Service Cisco-exec START###
    service = shell {
      set priv-lvl = 15
      default attribute = permit
      default cmd = permit
    } #END OF Cisco Router/Switch Service
    ###Service Cisco-exec END###
  } #END OF network-admins`

If not, I'll get back to you Monday when I'm able to test login again :)

**Comment by beepmeep88** [comment]
Thanks a lot for your reply.

I think I have an ACL called "Permit-all" applied to my group setting, which is based on IP adresses.. I suppose that's whats blocking the authentication.
I have to wait till Monday before I can confirm. Sorry for reporting this, thanks a lot for the help.. made me realize my mistake.

**Comment by beepmeep88** [comment]
My mistake. The ACL was the issue. thanks.
