### ISSUE TITLE
Enable password

### ISSUE THREAD

**Issue by rcsmota** [tacacsgui/tacacsgui#35]
Hi;

After update my tacacsgui from  0.9.42 to 0.9.63 all may devices start ask for enable password, even for users with privileges 15.

I try configure a service with priv 15 but always ask for enable password. 

![imagem](https://user-images.githubusercontent.com/31240306/55408481-f99f6780-5557-11e9-9b9d-da0c3185410d.png)

Is there a way to skip the request?

Ubuntu version: 18.04.2 LTS
PHP version: HP 7.3.3
TacacsGUI API version: 0.9.63

**Comment by gurkin33** [comment]
Hello,

Could you send me example of a user configuration that has issue, if user is a member of a group, the group configuration also required.

Best Regards, Aleksey

**Comment by rcsmota** [comment]
Hi @gurkin33 

I make some tests here and new users work without problem only imported to old version to new version have this problem.

**Imported user**

![imagem](https://user-images.githubusercontent.com/31240306/55411181-15f1d300-555d-11e9-9ab5-c18cd25087bf.png)

At GUI I can't change enable configuration

![imagem](https://user-images.githubusercontent.com/31240306/55411354-6b2de480-555d-11e9-9399-45a51cad9921.png)


**Group**

![imagem](https://user-images.githubusercontent.com/31240306/55411404-7ed94b00-555d-11e9-8dda-7c1fca1b453b.png)

**New User**

![imagem](https://user-images.githubusercontent.com/31240306/55411449-94e70b80-555d-11e9-9f7b-cb167cb2f9d7.png)

**Comment by gurkin33** [comment]
Hello,

Could you use **Ctrl+Shift+R** (browser cache will be deleted) and try to change enable password one more time?

Regards, Aleksey

**Comment by rcsmota** [comment]
Blessed Ctrl+Shift+R. After this i can remove the enable and now the enable is not asked.

Thanks @gurkin33

**Comment by gurkin33** [comment]
Nice to hear that. Enjoy a new version.

You can thank me, help the project and a developer via [Patreon](https://www.patreon.com/tacacsgui).
Best Regards, Aleksey
Developer of TacacsGUI
