### ISSUE TITLE
Enable HTTP(s) Tacacs Auth

### ISSUE THREAD

**Issue by juesor** [tacacsgui/tacacsgui#36]
Ubuntu version: 16.04.5
PHP version: PHP 7.3.3-1
TacacsGUI API version: 0.9.63
Browser: All

I would like to pass http(s) auth through TacacsGUI.

I am trying to http(s) login to a UniFi ToughSwitch.  SSH works but http(s) fails.

I can attach a packet capture if needed.

**Comment by gurkin33** [comment]
Hello,

Could you tell me, tacacs makes log entries about your authentication requests?

Best Regards, Aleksey

**Comment by juesor** [comment]
mavis_debug.txt

I tail the above file and then try a http(s) auth and i do not see anything happening.

**Comment by gurkin33** [comment]
Hello,

Unfortunately, I doesn't have  UniFi ToughSwitch and can't test, but I think the issue inside of device configuration - you have to check devices configuration and enable web authentication via tacacs. As you said above ssh works, but web authe doesn't.

Best Regards, Aleksey

**Comment by juesor** [comment]
Ok so Web Auth used to work through Cisco ACS platform.  TACACS was moved over to TacasGUI and now its broke is what i'm being told.

Like i mentioned.  I did a tcpdump and captured an authentication request.

I can see the ToughSwitch request.
I can see TacacsGUI go to my LDAP server and doing search
I can see the DC respond with bindResponse(3) success
Then i see TacacsGUI sends a response to the ToughSwitch 

Then i see TacacsGUI sends Syslog info to my GrayLog server:
514	20.088543	TacacsGUI	Graylog	Syslog	123	UUCP.INFO: Apr  5 11:09:19 ToughSwitch tacplus jkool\tunknown\t\tshell login succeeded

So really i'm not sure whats going on why it doesn't work.

**Comment by gurkin33** [comment]
Hello,

Nice description. Could you send me example of dump of traffic? Please send it on developer@tacacsgui.com. Also I have to have tacacs key to decrypt traffic.

Best Regards, Aleksey

**Comment by juesor** [comment]
Email was sent.

I'm working on gathering what you requested.

**Comment by gurkin33** [comment]
Hello Jeremy,

I will try to summarize all things that we have:

1. Authentication with local user works. Could you send user configuration?
2. When you add user group (which used for LDAP user) to the local user, authentication doesn't pass, right? Could you send configuration of that group?

Best Regards, Aleksey

**Comment by juesor** [comment]
Information was sent.

**Comment by gurkin33** [comment]
Issue has expired.
