### ISSUE TITLE
TAC GUI Stuck on updating page 

### ISSUE THREAD

**Issue by haseebakhtarhussain** [tacacsgui/tacacsgui#38]
**Describe the system**
Ubuntu version: 16.04.4
PHP version: 7.3
TacacsGUI API version: 0.9.63
Browser: chrome

**Describe the bug**
Whever i try to open TACGUI it stucks at updating page 
![image](https://user-images.githubusercontent.com/50142302/56962861-f1dfdc80-6b70-11e9-9cc6-2cd7557957a9.png)

i've tried to reinstall but every time it gets stuck on same page.

**Comment by gurkin33** [comment]
Hello,

Version 0.9.63 is [for Ubuntu 18.08](https://tacacsgui.com/documentation/installation/migration-from-ubuntu-16-04/). How did you try to re-install?

Regards, Aleksey

**Comment by haseebakhtarhussain** [comment]
Hi, 
Thanks for your response, actually i used [ old documentation](https://tacacsgui.com/documentation_old/system-reinstallation/), 


```
cd ~; sudo rm -r tgui_install*; wget https://github.com/tacacsgui/tgui_install/archive/tgui_install.tar.gz

mkdir tgui_install; tar -xvf tgui_install.tar.gz -C ~/tgui_install/ --strip-components 1; cd ./tgui_install

sudo chmod 755 ./tacacsgui.sh ; sudo ./tacacsgui.sh
```

**Comment by gurkin33** [comment]
Hello,

Could you try to repeat all steps (from download!) one more time, I have made some changes and if you get error with incorrect Ubuntu version, do next:

Open file: `nano ~/tgui_install/inc/src/func_general.sh`
and change next code from:
```
function check_ubuntu() {
  echo $(lsb_release -r -s | grep -oE "(18.04)" | wc -l | tr -d '[:space:]'); return;
}
```
to
```
function check_ubuntu() {
  echo 1; return;
}
```
I don't know what version was before, then please try to install all php packages:
```
sudo apt-get install -y php7.3 php7.3-common php7.3-cli php7.3-fpm \
php7.3-curl php7.3-dev php7.3-gd php7.3-mbstring \
php7.3-zip php7.3-mysql php7.3-xml libapache2-mod-php7.3 php7.3-ldap
```

Please, let me know a result.

Regards, Aleksey

**Comment by haseebakhtarhussain** [comment]
Now when i removed old files and downloaded and run new instillation script (from old documentation page) i get following error,

`###############################################################
##############   TACACSGUI Installation Script    ##############
###############################################################

ver. 2.0.0

##############     List of available options    ##############

1) Install TacacsGUI       5) Clear and Refresh Menu
2) Re-install TacacsGUI    6) Write to Log file
3) Network Settings        7) Quit
4) Test the System

Please enter your choice (5 to clear output): 2

### Re-install TacacsGUI ###


### Test the System ###

Done.  ### MySQL Installed  ###

###########    Error!    ###########
Error! Some Packages Not Installed! Try to install.
####################################
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                        
Hit:2 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu xenial InRelease                                 
Hit:3 http://linux.teamviewer.com/deb stable InRelease                                                                   
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                                               
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease                                  
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease       
Hit:7 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libnet-ldap-perl is already the newest version (1:0.6500+dfsg-1).
make is already the newest version (4.1-6).
python3-dev is already the newest version (3.5.1-3).
python3-mysqldb is already the newest version (1.3.7-1build2).
unzip is already the newest version (6.0-20ubuntu1).
zip is already the newest version (3.0-11).
libapache2-mod-xsendfile is already the newest version (0.12-2).
apache2 is already the newest version (2.4.18-2ubuntu3.10).
curl is already the newest version (7.47.0-1ubuntu2.12).
ldap-utils is already the newest version (2.4.42+dfsg-2ubuntu3.5).
libbind-dev is already the newest version (1:9.10.3.dfsg.P4-8ubuntu1.14).
libmysqlclient-dev is already the newest version (5.7.26-0ubuntu0.16.04.1).
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.9).
lwresd is already the newest version (1:9.10.3.dfsg.P4-8ubuntu1.14).
libpcre3-dev is already the newest version (2:8.42-1+ubuntu16.04.1+deb.sury.org+1).
openssl is already the newest version (1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
python3-mysqldb libmysqlclient-dev python3-dev make gcc openssl apache2 lwresd curl zip unzip libnet-ldap-perl ldap-utils ntp libapache2-mod-xsendfile libpcre3-dev:amd64 libbind-dev
We must have:
python3-mysqldb libmysqlclient-dev python3-dev make gcc openssl apache2 lwresd curl zip unzip libnet-ldap-perl ldap-utils ntp libapache2-mod-xsendfile libpcre3-dev:amd64 libbind-dev
We have:
apache2 curl gcc ldap-utils libapache2-mod-xsendfile libmysqlclient-dev libnet-ldap-perl libpcre3-dev:amd64 lwresd make ntp openssl python3-dev python3-mysqldb unzip zip
###########    Error!    ###########
Error! Some Packages Not Installed!
####################################
###########    Error!    ###########
Error was Found. Installation Stop!
####################################`

where as i already have all these packages installed 

`tacacs@ubuntu:~/tgui_install$ sudo apt-get install python3-mysqldb libmysqlclient-dev python3-dev make gcc openssl apache2 lwresd curl zip unzip libnet-ldap-perl ldap-utils ntp libapache2-mod-xsendfile libpcre3-dev:amd64 libbind-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libnet-ldap-perl is already the newest version (1:0.6500+dfsg-1).
make is already the newest version (4.1-6).
python3-dev is already the newest version (3.5.1-3).
python3-mysqldb is already the newest version (1.3.7-1build2).
unzip is already the newest version (6.0-20ubuntu1).
zip is already the newest version (3.0-11).
libapache2-mod-xsendfile is already the newest version (0.12-2).
apache2 is already the newest version (2.4.18-2ubuntu3.10).
curl is already the newest version (7.47.0-1ubuntu2.12).
ldap-utils is already the newest version (2.4.42+dfsg-2ubuntu3.5).
libbind-dev is already the newest version (1:9.10.3.dfsg.P4-8ubuntu1.14).
libmysqlclient-dev is already the newest version (5.7.26-0ubuntu0.16.04.1).
ntp is already the newest version (1:4.2.8p4+dfsg-3ubuntu5.9).
lwresd is already the newest version (1:9.10.3.dfsg.P4-8ubuntu1.14).
libpcre3-dev is already the newest version (2:8.42-1+ubuntu16.04.1+deb.sury.org+1).
openssl is already the newest version (1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
tacacs@ubuntu:~/tgui_install$`

**Comment by haseebakhtarhussain** [comment]
It turns out issue started because of me attempting HA configurations, when i did 
sudo rm /opt/tgui_data/ha/ha.*

**Comment by gurkin33** [comment]
Is it the same stuck page? Could you create HAR file ([here is example](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)) and send to developer@tacacsgui.com.

**Comment by haseebakhtarhussain** [comment]
Email sent with attached HAR file on stuck page, .

**Comment by haseebakhtarhussain** [comment]
Eventually the issue was  I was trying  HA without my slave being registered. so deleting `/opt/tgui_data/ha/ha.* ` resolves the issue.
