### ISSUE TITLE
IPv6 maximum prefix length too short

### ISSUE THREAD

**Issue by chucktastic** [tacacsgui/tacacsgui#39]
**Describe the system**
Ubuntu version: ... 
tacgui@zuul:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

PHP version: ... 
tacgui@zuul:~$ php -v
PHP 7.3.4-1+ubuntu18.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:51:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-1+ubuntu18.04.1+deb.sury.org+3, Copyright (c) 1999-2018, by Zend Technologies

TacacsGUI API version: **IMPORTANT** 
tacgui@zuul:~$ php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";'
0.9.63

Browser: [e.g. chrome, safari]
Chrome - Version 74.0.3729.131 (Official Build) (64-bit)

**Describe the bug**
When adding a device with an IPv6 address, the maximum prefix length is /32.  The appropriate maximum should be /128.

**To Reproduce**
1. Go to 'TACACS Devices - Devices'.
2. Click on '+Add Device'.
3. Enter IPv6 address in the "Device's IP Address" field.
4. Prefix slider maximum /32.

**Screenshots**
Screenshot attached.

**Additional context**
Prefix slider should extend to /128 when IPv6 address is entered or could simply be a text input box.
![IPv6 short prefix](https://user-images.githubusercontent.com/5589545/57949118-7c367900-78b1-11e9-9562-a2d583c5e65a.JPG)

**Comment by gurkin33** [comment]
Hello,

Thank you for your very informative description. I will add ipv6 support in a further version. I'm creating new version where the address will be like an object and you will be able to create one of 3 types of addresses - ipv4, ipv6, fqdn.

Best Regards, Aleksey.

**Comment by gurkin33** [comment]
Hello, I have added and tested IPv6 support in the new version 0.9.72. 
Please let me know if something will go wrong.

Regards, Aleksey

**Comment by chucktastic** [comment]
Performed the upgrade yesterday morning.  All seems to work as designed.  Thank you!
