### ISSUE TITLE
Валидатор конфига возвращает ошибку если в tacacs key присутствует символ "="

### ISSUE THREAD

**Issue by zirus00** [tacacsgui/tacacsgui#4]
Когда в ключе такакса есть символ равно, то валидатор конфигурации возвращает результат что в конфиге есть ошибки.

В качестве workaround пришлось использовать более простой ключ

**Comment by gurkin33** [comment]
Действительно есть такое, надо писать пароль в кавычках. Исправлю в ближайшем обновлении.

С Уважением, Алексей

**Comment by gurkin33** [comment]
Добрый день!
В версии 0.9.11 данная проблема решена. Просьба проверить. Спасибо!

**Comment by gurkin33** [comment]
Проблема решена.
