### ISSUE TITLE
Cannot connect to ldap

### ISSUE THREAD

**Issue by brancott** [tacacsgui/tacacsgui#40]
**Describe the system**
Ubuntu version: 18.04
(use next command: lsb_release -a )
PHP version: 7.3 
(use next command: php -v )
TacacsGUI API version: 0.9.63
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: chrome

I have tacacsgui and openldap installed on the same server. I configured Mavis LDAP following the tutorial and when I run Test connection it's successful and Check LDAP for any user gives me NAK result. However when I try to add LDAP user to a group in tacacs and go to LDAP tab it just tells me No results found and I'm stuck there. Is there something else I need to configure or am I doing something wrong?

**Comment by gurkin33** [comment]
Hello,

Sorry for delay. Your group should have objectclass = posixGroup attribute, does it have?

Regards Aleksey

**Comment by brancott** [comment]
Hi, sorry for late reply, created a group with posixGroup objectclass,it works now. Thanks!
