### ISSUE TITLE
Migrate Logs to new server

### ISSUE THREAD

**Issue by rcsmota** [tacacsgui/tacacsgui#41]
I would like in the Ubuntu server migration from 16.04 to 18.04 not to lose the history of the logs, these logs is very important. Is it possible for me to move the logs from one server to another?

Thank you very much.

**Comment by gurkin33** [comment]
Hello, 

If you want to move logs you should do that by yourself (mysqldump will help you). Sorry. Migration script move only configuration.

**Comment by rcsmota** [comment]
I can do this. I make a dump on actual server but can't access mysql on new server. The default password change in this new version?  (was tacgui)

**Comment by gurkin33** [comment]
Yes. For security reason it was changed to random password. You can find password in file -> /opt/tacacsgui/web/api/config.php (root password in the end of file)
