### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Izanatos** [tacacsgui/tacacsgui#42]
Hi,

After upgrading to the latest 0.9.7 i am getting some database timeout especially when I click ACL.

I tried to  look in all available logs but I just couldn't find anything obvious.

I deleted the database and recreated the schema using the installation script but i am getting the same issue.

Any Idea ?

A

**Comment by gurkin33** [comment]
Hello,

What does mean "database timeout especially when I click ACL"? Upgrade was successful and you got error in new menu (gui), is it?

Why you are deleted database? How did you do that? I mean could you tell me all steps.

Aleksey

**Comment by Izanatos** [comment]
sure,

So when I try to list the ACL using the GUI i get the pink "server error" message. after that I can list any tacacs user or devices or anything related to database access.

I tought, ok, maybe that's a database issue so I dropped the database and recreated it using the reinstallation script.

But even with a vanilla database the issue remains.

**Comment by gurkin33** [comment]
Could you create har file for me? Here is [some kind of instruction](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting). Just move to page with error and collect info (har file). Please send me that file on my email - developer@tacacsgui.com

Aleksey

**Comment by gurkin33** [comment]
Now I see, please do the next steps:

1. execute command `cd /opt/tacacsgui/ && sudo -u www-data git pull`
2. then do _full-upgrade_  `sudo apt update && sudo apt full-upgrade -y`

Hope it helps. Please let me know.

**Comment by Izanatos** [comment]
the update in TACACLCtrl.php definitely did the trick 👍 

Thanks
