### ISSUE TITLE
Centralized Management | Централизованное управление

### ISSUE THREAD

**Issue by faurik** [tacacsgui/tacacsgui#43]
Hello

Is it possible to realize the centralized management feature in the future updates? For example, if I had 2 or more servers with TACACS+ service on the different servers, it would be much more convenient to manage them centrally.

----
Добрый день.

Возможно ли реализовать функционал централизованного управления для будущих обновлений? Например, если у меня есть 2 или больше сервисов TACACS+ на разных серверах, было бы гораздо удобнее управлять ими централизованно.

**Comment by gurkin33** [comment]
Добрый день!
Я думаю, если до этого дойдёт, то это не ближайшее будущее. Поддержки практически нет, а планов и запросов много.
Мы можем попробовать вернуться к этому вопросу через год.

С Уважением, Алексей
