### ISSUE TITLE
Can't export/import devices

### ISSUE THREAD

**Issue by cgaeden** [tacacsgui/tacacsgui#44]
SYSTEM DESCRIPTION:

Originally deployed from OVA
```
tacgui@tacgui:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
tacgui@tacgui:~$ 
tacgui@tacgui:~$ php -v
PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
tacgui@tacgui:~$ 
tacgui@tacgui:~$ php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";'
0.9.72
tacgui@tacgui:~$ 

```
Browser: Chrome v75.0.3770.100 & Firefox v67.0.4 (both browsers 64-bit)

BUG DESCRIPTION:
I'm unable to export or import devices to/from CSV file. Selecting 'Export Selected' from the Actions menu button results in no visible action. This appears to be the case in your demo site as well (https://demo.tacacsgui.com:4443/auth/login)

**To Reproduce**

1. Clear cache and restart browser
2. Log in as administrative user
3. Click Tacacs Devices > Devices in the left column menu
4. Click on a device in the list of devices to highlight it
5. Click on the Actions button to expose the menu
6. Click on Export Selected

**Screenshots**
![TACACS Export Bug](https://user-images.githubusercontent.com/29563756/60371210-71412f00-99ad-11e9-94ec-d25d4bd10396.gif)

**Additional context**

**Comment by gurkin33** [comment]
Hello, 

I will fix that in one of a future version. Sorry.

Regards, Aleksey
You can help the project [Patreon.com](https://www.patreon.com/tacacsgui)

**Comment by cgaeden** [comment]
Thanks! Much appreciated!

**Comment by alessandro-deprato** [comment]
Hello,
Is there another way to add bulk devices?
Putting them manually to the file works but then any change done via the GUI erase the work done. I need to add around 2K devices and need an easy way...
Thank you

**Comment by gurkin33** [comment]
Hello,

I'm working on it, but I have some requests from user who bought a support. They are more preferred for me and I will do import/export after some other tasks. Please be patient.

Regards, Aleksey

**Comment by gurkin33** [comment]
Hello,

Export/Import added in version 0.9.81.

Regards, Aleksey
