### ISSUE TITLE
Configuration manager with AD doesn't work properly

### ISSUE THREAD

**Issue by ybshin** [tacacsgui/tacacsgui#46]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
(use next command: lsb_release -a )
PHP version: PHP 7.3.6-1
(use next command: php -v )
TacacsGUI API version: 0.9.72
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: [e.g. chrome, safari] Chrome

**Describe the bug**
Configuration manager is working but there is no output when run 'show run' command.
the buffer is empty after run 'show run' command.

**To Reproduce**
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/10042091/60428127-60e5ba00-9c22-11e9-8948-d50a77a5e5b8.png)

Models
![image](https://user-images.githubusercontent.com/10042091/60428158-74912080-9c22-11e9-8796-7a5932c50935.png)

**Additional context**

**Comment by ybshin** [comment]
I've tried to ssh from tacgui server and when I follow the command it works...

**Comment by gurkin33** [comment]
Hello, 

Could you try to add hostname to Default Prompt, like so **Router#** and try again? Default prompt for Configuration Manger (CM) is _>_ or _#_  and if a configuration has one of these sign CM works incorrectly.

Hope it helps.

**Comment by ybshin** [comment]
@gurkin33 
It works when I add default prompt list at Models but when I add default prompt list at each devices it doesn't work....

Work(Models)
![image](https://user-images.githubusercontent.com/10042091/60480459-ccc43300-9cb3-11e9-90fb-372bd6a48e87.png)

Doesn't work(Devices)
![image](https://user-images.githubusercontent.com/10042091/60480470-d9e12200-9cb3-11e9-9d2f-b6e9d0736d41.png)

**Comment by gurkin33** [comment]
Hello, 

Ok, I will check it and let you know the result. Thank you for your feedback.

Regards, Aleksey

**Comment by gurkin33** [comment]
Hello, 

It was fixed in version 0.9.73

Regards, Aleksey
