### ISSUE TITLE
System Info time bug

### ISSUE THREAD

**Issue by ybshin** [tacacsgui/tacacsgui#47]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
(use next command: lsb_release -a )
PHP version: PHP 7.3.6-1 
(use next command: php -v )
TacacsGUI API version: 0.9.72
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: [e.g. chrome, safari] chrome, firefox

**Describe the bug**
Month data is displaying 61 instead of 7

**To Reproduce**
3. See error

**Screenshots**
If you have screenshots to help explain your problem, feel free and attach them.
![image](https://user-images.githubusercontent.com/10042091/60555683-3ef64f80-9d68-11e9-91a2-d769705a9bdb.png)

**Additional context**

**Comment by gurkin33** [comment]
Hello,

Thank you. My bad. I will fix it.

Regards, Aleksey

**Comment by gurkin33** [comment]
Hello,

Fixed in version 0.9.73. Please check.

Regards, Aleksey

**Comment by ybshin** [comment]
> Hello,
> 
> Fixed in version 0.9.73. Please check.
> 
> Regards, Aleksey

No...Still same

![image](https://user-images.githubusercontent.com/10042091/61425181-4a3ca400-a940-11e9-8ca1-4a0e9b1a1315.png)

**Comment by gurkin33** [comment]
Hello,

`Ctrl + Shift + R` or `Cmd + Shift + R` (for Mac). Your browser cached old script.

Regards, Aleksey

**Comment by ybshin** [comment]
> Hello,
> 
> `Ctrl + Shift + R` or `Cmd + Shift + R` (for Mac). Your browser cached old script.
> 
> Regards, Aleksey

Fixed. Thank you!
