### ISSUE TITLE
unable to delete user group

### ISSUE THREAD

**Issue by johol** [tacacsgui/tacacsgui#48]
**Describe the system**
Description:    Fedora release 30 (Thirty)
(use next command: lsb_release -a )
PHP version: PHP 7.3.6
(use next command: php -v )
TacacsGUI API version: 0.9.72
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: firefox

**Describe the bug**
I'm trying to delete a user group, but the group is not deleted.
I only get a "Server Error" message.

**To Reproduce**
1. Go to 'Tacacs User Group'
2. Click on the trash icon
3. See error

**Comment by gurkin33** [comment]
Hello,

As I thing it is because one of user is a member of that group. Please check that. I will add more clear error message later for that situation.

Regards, Aleksey

**Comment by johol** [comment]
Hello Aleksey,
thank you for your quick reply. I think the problem is, that there is a service configured.
Here the part from the config file for the group which is not possible to delete.
  group = delete-me {
    enable = crypt $1$HEj8BeNr$MVUsheSIE0jYG8Op95N/P.
    default service = permit
    ###Service cisco-level-15 START###
    service = shell {
      set priv-lvl = 15
      default attribute = permit
      default cmd = permit
    }

I removed the service. The config file is
  group = delete-me {
    enable = crypt $1$HEj8BeNr$MVUsheSIE0jYG8Op95N/P.
    default service = permit
  }

Now it is possible to delete the group.

Regards,
Jörg

**Comment by gurkin33** [comment]
Thank you, Jörg

I will keep it in mind and try to make that process more clear.

Regards, Aleksey
