### ISSUE TITLE
Сервис по-умолчанию в генерируемом конфиге

### ISSUE THREAD

**Issue by zirus00** [tacacsgui/tacacsgui#5]
По-дефолту пользователи в генерируемом конфиге создаются с сервисом shell
С таким сервисом tac_plus на все запросы от Cisco возвращает authorization deny, даже если privilege level стоит 15
Для себя решил добавлением service exec:
service = exec { set priv-lvl = 15 }

Наверное надо заменить в генераторе конфига сервис для которого задаются настройки

**Comment by gurkin33** [comment]
Добрый день! Видимо, все зависит от устройства. Подскажите, какое устройство вы добавляете? Надо ли к этому устройству так же добавлять service = shell ...?

**Comment by zirus00** [comment]
Кажется тут возникла рассинхронизация при проведении начальной конфигурации, при применении новой конфигурации такакс или не рестартуется или делает это медленно.
Я удалил сервис exec и все продолжило работать, сделал packet capture трафика такакс, во всех запросах приходит service = shell.

Но сейчас проверил другое устройство на Cisco WLC используется сервис service = ciscowlc, для авторизации установил для этого сервиса параметр "set role1 = ALL"
Я заведу отдельное issue про tacacs для WLC когда разберусь как точно его настраивать.

В докуметации для Cisco ISE написано следующее

> WLC uses TACACS+ Custom Attributes, which need to be defined as role1, role2, etc. The available roles are MONITOR, WLAN, CONTROLLER, WIRELESS, SECURITY, MANAGEMENT, COMMAND, ALL, and LOBBY. The first seven correspond to the menu options on the WLC admin web UI. You may enter one or more roles to allow read and write access to the particular features, and read-only for the rest.
To grant read and write access to WLAN, SECURITY and CONTROLLER, then enter the following text:
role1=WLAN
role2=SECURITY
role3=CONTROLLER

Еще я видел что для авторизации на Juniper нужно настраивать сервис junos-exec. Этот issue я закрою, но думаю можно сделать вывод что нужна возможность управления сервисами и задания множества сервисов для пользователя
