### ISSUE TITLE
Applied User and Device Groups limit = 1

### ISSUE THREAD

**Issue by chucktastic** [tacacsgui/tacacsgui#50]
Version 0.9.73

**Describe the bug**
0.9.73 only allows one user group or device group to be applied.

Previous version would allow multiple user groups and device groups (under access control) to a user's profile.

Previously the UI would allow this:
  user = user1 {
    login = mavis # Local Database
    member = usergroup1/usergroup2/usergroup3
    default service = permit
  } #END OF user1

Now only one group may be applied:
  user = user2 {
    login = mavis # Local Database
    member = usergroup1
    default service = permit
  } #END OF user1

**Comment by gurkin33** [comment]
Hello,

My bad. Sorry, I will fix that this week.

Regards, Aleksey

**Comment by gurkin33** [comment]
Hello,

Fixed in version 0.9.74

Regards, Aleksey
