### ISSUE TITLE
user can login without a password

### ISSUE THREAD

**Issue by eds-ch** [tacacsgui/tacacsgui#52]
**Describe the system**
Ubuntu version: 18.04  ISO image that was downloaded from tacacsgui.com 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
PHP version:
PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 10 2019 06:54:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

TacacsGUI API version:0.9.73
**Describe the bug**

Users that are known by tacacsgui (created localy or from LDAP group) can login on Cisco router with just hitting Enter. If user is not known by tacacsgui it cant login.

**To Reproduce**

Create a user, login with username, instead of entering password just hit Enter.
EDIT:
Option  Change Password via NAS CLI in MAVIS Settings must be disabled

It maybe my configuration problem, but I can't imaging how this is can happen even with not correct config.

**Comment by gurkin33** [comment]
Hello,

When I type nothing to Password field all my Cisco devices say that I can change the password, Juniper says the same.
I don't know what to suggest you. Can you try to disable default service inside of user settings?

Regards, Aleksey

**Comment by eds-ch** [comment]
Hello, I have this option (option to change password) diabled. Can you please disable it on your server and check it again?

**Comment by gurkin33** [comment]
Sorry. I can't reproduce your issue. I tried to disable change password function and empty password give error - Password incorrect.

Something wrong with your configuration.

Regards, Aleksey

**Comment by gurkin33** [comment]
Can you send me or put here part of log from /var/log/tacacsgui/mavis_debug.txt where you authenticate without password?

**Comment by eds-ch** [comment]
No I can't reproduce it again. Now when I disable Change Password option, everything works fine. Not sure what it was. And mavis_debug.txt is clearing after new options applied, so I cant get old logs. 
I will write if it will happen again. Thanks for your help.

**Comment by gurkin33** [comment]
Hello,

It was a bug. After first successful login, user could authenticate without password because password variable was saved. That was fixed in version 0.9.75.
Regards, Aleksey
