### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by dnyt84** [tacacsgui/tacacsgui#53]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
(use next command: lsb_release -a )
PHP version: PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1 
TacacsGUI API version: 0.9.74

Browser: Chrome

**Describe the bug**
Can't test and apply config after setting up LDAP

**To Reproduce**
I took a fresh install, configured Mavis Ldap for Openldap

When I click on Test it works. Save is ok.
The LDAP Grops lists my groups as well.
No problems.

Under Tacacs Configuration -> Test and Apply
I uncheck "Make backup after applying"
and click on Test I get the following error:
"11150: /opt/tacacsgui/tac_plus.cfg_test:33: Expected 'same', 'user', 'group-membership', 'hide-version', 'checksum', 'set', 'event' or '||', but got 'exec' 11150: Detected fatal configuration error. Exiting."
Line 33 is the mavis exec, here is the configuration sniplet:

28  ####MAVIS GENERAL SETTINGS####
29  user backend = mavis
30  login backend = mavis chpass
31  pap backend = mavis
32  mavis module = external {
33   exec = /opt/tacacsgui/mavis/app.php
34  } #END OF MAVIS GLOBAL SETTINGS

**Additional context**

I resinstalled everything fresh and from default. I will got the same error.

**Comment by gurkin33** [comment]
Hello,
Sorry, but I can't recreate the issue. Could you give me the part of /opt/tacacsgui/tac_plus.cfg_test with MAVIS settings? Please, take that part of config immediately after error appearing.

**Comment by dnyt84** [comment]
####SPAWND####
id = spawnd {
  listen = { port = 49 }
} ##END OF SPAWND
####GENERAL CONFIGURATION####
id = tac_plus {
  ###MANUAL CONFIGURATION START###
log = accounting_log {
        destination =  "| /opt/tacacsgui/parser/tacacs_parser.sh accounting"
        log separator = "|!|"}
log = authentication_log {
        destination = "| /opt/tacacsgui/parser/tacacs_parser.sh authentication"
        log separator = "|!|"}
log = authorization_log {
        destination = "| /opt/tacacsgui/parser/tacacs_parser.sh authorization"
        log separator = "|!|"}
  ###MANUAL CONFIGURATION END###
  accounting log = accounting_log
  authentication log = authentication_log
  authorization log = authorization_log
  connection timeout = 600
  context timeout = 3600
  password max-attempts = 1
  password backoff = 1
  separation tag = "*"
  skip conflicting groups = yes
  skip missing groups = yes
  ####MAVIS GENERAL SETTINGS####
  user backend = mavis
  login backend = mavis chpass
  pap backend = mavis
  mavis module = external {
    exec = /opt/tacacsgui/mavis/app.php
  } #END OF MAVIS GLOBAL SETTINGS
  ####LIST OF ACL####
  ####LIST OF DEVICE GROUPS####
  host = defaultGroup {
    welcome banner = "Unauthorized access is prohibited!"
    motd banner = "Today is a perfect day! Have a nice day!"
    failed authentication banner = "Go away! Unauthorized access is prohibited!"
  } #END OF defaultGroup
  ####LIST OF HOSTS####
  host = xxx.xx.xx {
    address = "xxx/32"
    key = "xx"
    enable = clear "xx"
    template = defaultGroup
  } #END OF xx.xx.xx
  ####LIST OF USER GROUPS####
  group = defaultUserGroup {
    default service = deny
  } #END OF defaultUserGroup
  group = netops {
    #### LDAP Groups List #### DistinguishedName ###
    ### cn=netops,cn=groups,cn=accounts,dc=pop
    enable = clear "xxx"
    default service = permit
  } #END OF netops
  ####LIST OF USERS####
  user = admin {
    login = clear "test"
    enable = clear ""
  } #END OF admin
}##END GLOBAL CONFIGURATION

**Comment by gurkin33** [comment]
Hello, 

Sorry, but I still can't recreate your issue. You can try to rebuild tac_plus daemon, maybe it is fix your issue.

Regards, Aleksey

**Comment by dnyt84** [comment]
downloaded latest version of tac_plus daemon and recompiled but same problem.
Test Configuration
26310: /opt/tacacsgui/tac_plus.cfg_test:33: Expected 'same', 'user', 'group-membership', 'hide-version', 'checksum', 'set', 'event' or '||', but got 'exec' 26310: Detected fatal configuration error. Exiting.


I have no data on the server, reinstalled ubuntu and started from scratch, same error...

**Comment by jozwikjp** [comment]
@dnyt84   Did you ever get this resolved, have the same error upgraded from ubuntu 18 to 20 and rebuild the tac_plus daemon.
