### ISSUE TITLE
Anonymous searches on LDAP config

### ISSUE THREAD

**Issue by Jomura81** [tacacsgui/tacacsgui#54]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
TacacsGUI API version: 0.9.73
Browser: [Mozilla Firefox]

**Describe the bug**
I can't do anonymous searches when I configure MAVIS LDAP

**Context**
I had configured my MAVIS LDAP with a Username and Password, everything works.
My LDAP is configured to support anonymous searches.
But when I want to do anonymous searches, I let the username and password forms empty. And when I do the test, I have the following message : Invalid credentials.

**Comment by gurkin33** [comment]
Hello,

Anonymous search not allowed. 

Could you please give me info how do you want to use it in your environment and I will think about that feature.

Regards, Aleksey

**Comment by Jomura81** [comment]
Hello, thank you for your quick answer. 
Our LDAP is configure with anonymous searches, and we use this functionality for all our services. It is very useful because we haven't to create a service user for each services. 

Thank you,
best regards, 
Joris
