### ISSUE TITLE
Unrecognized token '0' 

### ISSUE THREAD

**Issue by llawwehttam** [tacacsgui/tacacsgui#55]
**Describe the system**
Ubuntu version: Ubuntu 18.04.3 LTS
PHP version: PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
TacacsGUI API version: 0.9.76
Browser: Chrome

When I try to save the config I get the following:

1620: /opt/tacacsgui/tac_plus.cfg_test:28: Unrecognized token '0' 1620: Detected fatal configuration error. Exiting.

I can see the following in the config:

```
  ###MANUAL CONFIGURATION END###
  accounting log = accounting_log
  authentication log = authentication_log
  authorization log = authorization_log
  connection timeout = 600
  context timeout = 3600
  password max-attempts = 1
  password backoff = 1
  separation tag = "*"
  skip conflicting groups = yes
  skip missing groups = yes
0
  ####LIST OF ACL####
```

The "0" on it's own causes the problem.
![Screenshot 2019-08-20 at 12 36 44](https://user-images.githubusercontent.com/1150695/63343956-302f2080-c347-11e9-96fe-1521f10bff6f.png)

**Comment by llawwehttam** [comment]
Is it possible for me to clear the changes and return to the current configuration?

**Comment by gurkin33** [comment]
Hello,

Could you upgrade it to version 0.9.77 and try again?

Please, let me know the result.

Regards, Aleksey

**Comment by llawwehttam** [comment]
Thanks Aleksey,

That's fixed now.
