### ISSUE TITLE
how to use ldap for API

### ISSUE THREAD

**Issue by dnyt84** [tacacsgui/tacacsgui#57]
I added the LDAP group into the API user group however I can't use my ldap account to sign in.
Are there any other steps required?

**Comment by gurkin33** [comment]
Hello,

I've just tested and everything works for me. What I have done:

1. checked connection to LDAP Server (MAVIS LDAP). 
2. added LDAP group to the TACACSGUI. 
3. checked that a LDAP User (_ldapuser1_) belong to LDAP group.
4. created new API User Group and made assosiation with LDAP Group from step 2. 
5. !! I've added Administrator rights to API group!!
6. finally, I've tried to login with _ldapuser1_ and get success.

Hope it will help you.

Regards, Aleksey

**Comment by gurkin33** [comment]
Issue is out of date. Closed
