### ISSUE TITLE
Clone Login Password - tacacs group

### ISSUE THREAD

**Issue by dnyt84** [tacacsgui/tacacsgui#58]
Ubuntu version: Ubuntu 18.04.2 LTS
PHP version: PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1
API: 0.9.78
TAC: 201906100936/PCRE/DES/LWRES

Browser:  Chrome

When I try to Create or Edit a group and select Type: "Clone Login Password"
I get an error that the Enable Password can't be empty.

Tacacs Users -> User Groups 
Add or edit group

**Comment by gurkin33** [comment]
Hello,

Sorry, my bad. That option is not available for the Tacacs User Group. I'll remove it next update.

Please, use this option inside tacacs user settings.

Regards, Aleksey
