### ISSUE TITLE
HA issue after upgrading to 0.9.79

### ISSUE THREAD

**Issue by apedroamarques** [tacacsgui/tacacsgui#59]
Hello,

After upgrading two TACACSGUI servers that where configured in a master/slave environment (for the upgrade the HA was removed and in the end, after the upgrade, it was again configured as we previous did in all past versions), we are unable to start the HA feature.

**Both servers use the same system, PHP and TacacsGUI API version**
Ubuntu version:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

PHP version:
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

TacacsGUI API version:
0.9.79

Browser:
Chorme, Mozilla Firefox

**Bug description**
In the master everything is ready to receive slave connections, the configuration is applied correctly and no issues presented, but when we try to add a slave we receive the error: "Error: Can't check activation" in the log we don't find any point that could lead us in to the right direction to solve the issue.
If we invert the process (the slave becomes the master), no issues are presented in the Master creation, but the slave always present that error.

Thank you.

**Comment by gurkin33** [comment]
Hello,

To make HA, you have to buy more installation entries to your account on tacacsgui.com or TACACSGUI support.

Thank you.
Regards, Aleksey
