### ISSUE TITLE
Reports no data found (accounting / authentication / authorization) 

### ISSUE THREAD

**Issue by Djamelito** [tacacsgui/tacacsgui#60]
**Describe the system**
Ubuntu version: 
-----------------------------------------------
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic
------------------------------------------------
PHP version: 
------------------------------------------------
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
------------------------------------------------
TacacsGUI API version: **IMPORTANT** 
------------------------------------------------
0.9.79
------------------------------------------------
Browser: [e.g. chrome, safari]
Version 76.0.3809.132 (Build officiel) (64 bits)
IE 11

describe the bug : 
"First installation"
there is no reports on web (auth / autho / accounting ) "no data found" 
regarding "gui log" this is working.

i checked on local file in ubuntu  "/var/log/tacacsgui/tac_plus"
folders are present for each days and i can find some details in the log file but not into web pages.
![image](https://user-images.githubusercontent.com/55450809/65054539-011fc500-d96e-11e9-8ec3-d8e94dc9b626.png)

thx for this project !

**Comment by gurkin33** [comment]
Hello,

Could you please upgrade to version 0.9.80 and let me know if it resolve the issue?

Regards, Aleksey

**Comment by Djamelito** [comment]
Good Morning Aleksey ! 

Many thx it's working now !

regards.
Djamel
