### ISSUE TITLE
LDAP error (ldap_control_paged_result_response)

### ISSUE THREAD

**Issue by lsinclair** [tacacsgui/tacacsgui#61]
**Describe the system**
Ubuntu version: Ubuntu 18.04.3 LTS
PHP version: 7.3.9
TacacsGUI API version: 0.9.80
Browser: Chrome

**Describe the bug**
Clean install from the Ubuntu ISO hosted on the website, everything is working fine but LDAP. I'm currently getting this error. I have created a new user on LDAP with access to view groups etc.. but getting this error back from the apache logs 

```[Mon Sep 30 14:14:08.385115 2019] [php7:warn] [pid 850] [client 217.68.240.34:4697] PHP Warning:  ldap_control_paged_result_response(): Result is: Referral (10) in /opt/tacacsgui/web/api/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 367, referer: http://217.69.33.131/mavis/ldap```

LDAP show connected and logins but no matter what I do this error still seems to show.

Thank you for taking the time to read.

**Comment by gurkin33** [comment]
Hello, 

Is everything ok now?

Regards, Aleksey
