### ISSUE TITLE
Network interface doesn't appear anymore on tacacsgui web

### ISSUE THREAD

**Issue by andretlemos** [tacacsgui/tacacsgui#62]
goadm@hades:/tmp/tgui_install-2.0.1$ php -v
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
goadm@hades:/tmp/tgui_install-2.0.1$ 
goadm@hades:/tmp/tgui_install-2.0.1$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Hi,

Today I noticed that tacacsgui web interface isn't recognized the network address anymore, but if I go on the command line on server and test the system the ens160 is configured. I tried to reinstall but didn't have any effect.

Also I think it's consequence, the key to activate the system online is not available.

![image](https://user-images.githubusercontent.com/5272728/66042806-e021ad00-e4f3-11e9-83be-15dd06ce2fb5.png)

**Comment by gurkin33** [comment]
Hello,

It is common issue after migration from Ubuntu 16 to 18 version. Please, configure _netplan_ manually and then it will work. [Here is example](https://tacacsgui.com/documentation/installation/ova/change-ip-address/#change_netplan) of manual configuration (_change netplan configuration file_). 
Hope it will help.

Regards, Aleksey

**Comment by andretlemos** [comment]
Thanks, you can close it.
