### ISSUE TITLE
running scripts 

### ISSUE THREAD

**Issue by bryanster** [tacacsgui/tacacsgui#64]
hi i have an idea for improving te capabilities of this platform 
how about a plugin to run "scripts" on 1 or multiple devices

**Comment by gurkin33** [comment]
Hello,

Could you give more info about that? Does it mean run one by one commands on device?

Regards, Aleksey

**Comment by bryanster** [comment]
well at the company i work for we have this  remote controle software we use for windows desktop management wich has the ability to run scripts(bat en ps1) scripts on one or multiple device

**Comment by gurkin33** [comment]
Sorry, I didn't understand what script did you mean? Could you give example of script? Does Cisco use scripts or another vendor? Could you give me as more info as you can? 

Regards, Aleksey

**Comment by bryanster** [comment]
hi most network equipment vendors dont have a scripting language so maybe what i am trying to achieve is harder then i realized
