### ISSUE TITLE
juniper vmx tac authentication 

### ISSUE THREAD

**Issue by jasonjiangxinhui** [tacacsgui/tacacsgui#65]
**Describe the system**
Ubuntu version: Ubuntu 18.04.2 LTS
(use next command: lsb_release -a )
PHP version: PHP 7.3.8
(use next command: php -v )
TacacsGUI API version: 0.9.82
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: [e.g. chrome, safari]
chrome
**Describe the bug**
juniper vmx authentication fail.
I think bug is "not found: svcname=junos-exec@vmx-3 protocol=."
it should be service not svcname
my debug information below;

30798: 01:23:13.847 1/5deca804: 192.168.0.13 user 'jiangxh' found
30798: 01:23:13.847 1/5deca804: 192.168.0.13 cfg_get: checking user/group jiangxh, tag (NULL)
30798: 01:23:13.847 1/5deca804: 192.168.0.13 jiangxh@192.168.0.13: not found: svcname=junos-exec@vmx-3 protocol=
30798: 01:23:13.847 1/5deca804: 192.168.0.13 jiangxh@192.168.0.13: not found: svcname=junos-exec protocol=
30798: 01:23:13.847 1/5deca804: 192.168.0.13 nas:service=junos-exec (passed thru)

####SPAWND####
id = spawnd {
  listen = { port = 49 }
} ##END OF SPAWND
####GENERAL CONFIGURATION####
id = tac_plus {
  ###MANUAL CONFIGURATION START###
log = accounting_log {
	destination =  "| /opt/tacacsgui/parser/tacacs_parser.sh accounting" 
	log separator = "|!|"} 
log = authentication_log {
	destination = "| /opt/tacacsgui/parser/tacacs_parser.sh authentication"
	log separator = "|!|"}
log = authorization_log {
	destination = "| /opt/tacacsgui/parser/tacacs_parser.sh authorization"
	log separator = "|!|"}
  ###MANUAL CONFIGURATION END###
  accounting log = accounting_log
  authentication log = authentication_log
  authorization log = authorization_log
  connection timeout = 600
  context timeout = 3600
  password max-attempts = 1
  password backoff = 1
  separation tag = "*"
  skip conflicting groups = yes
  skip missing groups = yes
  ####MAVIS GENERAL SETTINGS####
  user backend = mavis
  login backend = mavis chpass
  pap backend = mavis
  mavis module = external {
    exec = /opt/tacacsgui/mavis/app.php
  } #END OF MAVIS GLOBAL SETTINGS
  ####LIST OF ACL####
  ###ACL AS136800-MEGA-TOW-ST START###
  acl = AS136800-MEGA-TOW-ST permit {
    # nac = any
    nas = 103.198.146.162
  }
  ####LIST OF DEVICE GROUPS####
  host = defaultGroup {
    key = "juniper123"
    welcome banner = "Unauthorized access is prohibited!"

VMX configuration

set version 14.1R1.10
set system authentication-order tacplus
set system authentication-order password
set system root-authentication encrypted-password "$1$grU02cPa$C/xdt4PY6C5XpMnnHPhZp/"
set system tacplus-server 192.168.0.33 secret "$9$Z3DHmz39O1hfT1hSr8LGDikfTFn/t0B"
set system accounting events login
set system accounting events change-log
set system accounting events interactive-commands
set system accounting destination tacplus server 192.168.0.33 secret "$9$Y44JD.PQ9A0ikA0BIrl24aZikmfT3/C"
set system login user OP uid 2001
set system login user OP class operator
set system login user SU uid 2002
set system login user SU class super-user
set system login user lab uid 2003
set system login user lab class super-user
set system login user lab authentication encrypted-password "$1$jxIoJBGM$i0I.G7y6M9jExfUDdSmDZ."
set system services ssh
set system services telnet
set system syslog user * any emergency
set system syslog file messages any notice
set system syslog file messages authorization info
set system syslog file interactive-commands interactive-commands any
set interfaces ge-0/0/0 unit 0 family inet address 192.168.0.11/24

device log

Oct 21 16:47:54   login[3927]: LOGIN_PAM_USER_UNKNOWN: Attempt to authenticate unknown user jiangxh
Oct 21 16:47:54   login[3927]: User 'remote' authenticated successfully but no local login-id configured

**To Reproduce**
3. See error

**Screenshots**
If you have screenshots to help explain your problem, feel free and attach them.

**Additional context**

**Comment by gurkin33** [comment]
Hello,

Did you create user jiangxh?

Regards, Aleksey

**Comment by jasonjiangxinhui** [comment]
yes, it authencated successful,but can't login.

2019-10-21 23:56:37localhost192.168.0.11jiangxh192.168.0.33shell login succeeded
2019-10-21 23:57:47localhost192.168.0.11jiangxh192.168.0.33shell login succeeded
2019-10-21 23:58:02localhost192.168.0.11jiangxh192.168.0.33shell login succeeded
2019-10-22 00:24:17localhost192.168.0.11jiangxh192.168.0.33shell login succeeded
2019-10-22 00:37:59localhost192.168.0.11jiangxh192.168.0.33shell login succeeded



here is device loogging

Oct 21 16:47:54   login[3927]: User 'remote' authenticated successfully but no local login-id configured.

Oct 21 16:47:54   login[3927]: User 'remote' authenticated successfully but no local login-id configured.
Oct 21 16:47:54   login[3927]: LOGIN_FAILED: Login failed for user jiangxh from host 192.168.0.33
Oct 21 16:51:38   login[3927]: LOGIN_TIMED_OUT: Login attempt timed out after 120 seconds
Oct 21 16:51:38   login[3927]: 1 LOGIN FAILURE FROM 192.168.0.33




357160108@qq.com
 
From: Aleksey
Date: 2019-10-21 19:55
To: tacacsgui/tacacsgui
CC: xinhui jiang; Author
Subject: Re: [tacacsgui/tacacsgui] juniper vmx tac authentication (#65)
Hello,
Did you create user jiangxh?
Regards, Aleksey

**Comment by gurkin33** [comment]
Does it has Service for juniper?

**Comment by jasonjiangxinhui** [comment]
yes, u can also login my tacacs server for checking this issue.thank you very much
https://103.43.13.76:4443/dashboard
user: read
pass: read1234





357160108@qq.com
 
From: Aleksey
Date: 2019-10-21 20:00
To: tacacsgui/tacacsgui
CC: xinhui jiang; Author
Subject: Re: [tacacsgui/tacacsgui] juniper vmx tac authentication (#65)
Does it has Service for juniper?

**Comment by gurkin33** [comment]
Please, close the access right now. It is very insecure to get public access.

**Comment by jasonjiangxinhui** [comment]
it's my testing environment. when I test that work find. I am going to close it. thanks

and it's only read access for tacgui.


357160108@qq.com
 
From: Aleksey
Date: 2019-10-21 20:10
To: tacacsgui/tacacsgui
CC: xinhui jiang; Author
Subject: Re: [tacacsgui/tacacsgui] juniper vmx tac authentication (#65)
Please, close the access right now. It is very insecure to get public access.

**Comment by gurkin33** [comment]
You can find tacacs user configuration in [demo](https://demo.tacacsgui.com:4443) and device configuration [here](https://old.tacgui.com/documentation/device-configuration/juniper/juniper-vmx/juniper-vmx-configuration/).
You can try to connect to demo juniper device and see it works well.
If you will have more question, please try to make support request via tacacsgui.com.

Regards, Aleksey

**Comment by jasonjiangxinhui** [comment]
I did check it everything. unfortunately it does not work.

Connection closed by 192.168.0.13 port 22
root@tacgui:~# ssh jiangxh@192.168.0.13
Unauthorized access is prohibited!
Password: 
Today is a perfect day! Have a nice day!
the problem, it is still same.

**Comment by jasonjiangxinhui** [comment]
I find out the problem.thanks
I still think, it's a but. when my service related to a user. it works fine. but my service related to the user group.it can't work.it was work find on the old version.

**Comment by gurkin33** [comment]
Hello,
I think if you will get official support, it will help you.
I will close the ticket.
Regards, Aleksey
