### ISSUE TITLE
pammavis not built by default

### ISSUE THREAD

**Issue by novafiddler** [tacacsgui/tacacsgui#67]
pammavis is not built by default.

**Comment by gurkin33** [comment]
Hello,
Could you give me more info?
Regards, Aleksey

**Comment by novafiddler** [comment]
For authentication purposes, I need to use PAM (the pam_freeotp pam module). Pammavis (the executable) is needed to accomplish this correctly. The source file is there, but the executable is not there.

Pammavis does not exist in the tacacsgui setup as it is now. It should be built into tac_plus (enabled by argument passed at config time). I wound up compiling tac_plus myself on centos to get the functionality I was looking for.

**Comment by gurkin33** [comment]
You can recompile tac_plus as you want, with any additional attributes. 
Does lack of PAM module influence on tacacsgui work? As I understood you use it personally, is it?

**Comment by novafiddler** [comment]
The lack of PAM module does not influence tacacs, but the lack of a well documented feature:

http://www.pro-bono-publico.de/projects/mavis.html (see chapter 5)

is missing from your default setup. That's all I was saying. There's no need to be nasty, Sir.

**Comment by gurkin33** [comment]
Sorry for misunderstanding. Could we try from beginning?

Could you give me more info how do you use PAM module?
Do you have any ideas how I can add it to tacacsgui?

Regards, Aleksey

**Comment by gurkin33** [comment]
Also. Could you give me example of tac_plus config where you use that module?

**Comment by novafiddler** [comment]
Sure, no problem.

I downloaded your default ova, which was well packaged and easy to install. At this time I use WebADM/FreeOTP for single sign on of everything in my domain. all auth requests must pass through it. I only mention these things to describe my personal use case.

To authenticate without using radius, I installed pam_openotp authentication module to authenticate locally to webadm and sync active directory users and groups through webadm. This works very easilly.

**Now the part that matters to tac_plus:** I need to use pammavis so mavis can use PAM (local login module on the machine) via the external mavis module to authenticate users. 

When PAM ability is compiled into tac_plus, this all works successfully.

**Comment by gurkin33** [comment]
Could you give me configuration example for tac_plus?

**Comment by novafiddler** [comment]
Here is my config:

**BEGIN**
id = spawnd {
	listen = { 
		port = 49
		}
	spawn = {
		instances min = 1
		instances max = 10
	}
	background = yes
}

id = tac_plus {
	access log = /var/log/tac_plus/access/%Y%m%d.log
	accounting log = /var/log/tac_plus/acct/%Y%m%d.log
	debug = AUTHOR AUTHEN ACCT CONFIG CMD AV MAVIS
	

	mavis module = external {
		exec = /usr/local/sbin/pammavis pammavis -s tacacs
	}
	user backend=mavis
	login backend = mavis
	host = special {
		address = 172.16.0.116 key = test
		motd banner  = "\nWelcome to the foundry\n\n"
		failed authentication banner = "Authentication FAILED"
		enable 15 = clear testenable
		prompt = "Welcome\n"
		
	}
	group = admin {
		service = shell{
		default command = permit
		default attribute = permit
		set priv-lvl = 15
		}
	}

	
	user = ohnouser {
		login = mavis
		password = mavis member = admin 
		member = admin
		service = shell{
			default command = permit
			default attribute = permit
			set priv-lvl = 15
		}
	}
}
**END**

for "tacacs" in the command: exec = /usr/local/sbin/pammavis pammavis -s tacacs 

there is a file in /etc/pam.d/tacacs with the following:
**BEGIN**
auth       required    pam_env.so
auth       sufficient   pam_unix.so
auth       sufficient   pam_openotp.so client_id="TACACS" 
auth       required    pam_deny.so

**END**

for "client_id" above, a policy in webadm was established with the name 'TACACS' to establish authentication parameters.

**Comment by gurkin33** [comment]
Ok. Then you can disable all mavis modules (ldap, local, otp and sms) on tacacsgui and add your own inside of Global Settings -> Manual Configuration (in the bottom of the page):
```
mavis module = external {
	exec = /usr/local/sbin/pammavis pammavis -s tacacs
}
user backend=mavis
login backend = mavis
```
I think it should work.

**Comment by novafiddler** [comment]
That's just it, "/usr/local/sbin/pammavis" is missing and I cannot get tac_plus to compile on ubuntu 18.04 with your original options plus "--with-pam" added. I also installed libpam via apt-get as well before you ask. I keep getting errors. That's why I had to compile it on centos. 

The config above does work.

**Comment by gurkin33** [comment]
Unfortunately, I doesn't have enough time to go deeper to your issue. 
I think you should try to resolve issue first of all. Try to get clear Ubuntu distro and compile tac_plus with pam module, if you get success, then install tacacsgui.
Regards, Aleksey

**Comment by novafiddler** [comment]
After running your install script, the following worked for me on Ubuntu 18.04:

apt-get install gcc make libpcre3-dev libbind-dev libpam0g-dev libssl1.0-dev

echo "NOTE: THIS WILL NOT BUILD WITHOUT 'libssl 1.0' installed!"
cd ~

wget http://www.pro-bono-publico.de/projects/src/DEVEL.tar.bz2
tar xvfj DEVEL.tar.bz2
rm -rf DEVEL.tar.bz2

cd PROJECTS

ln -s /usr/include/security ./pam

./configure --prefix=/opt/tacacsgui --with-pam=/usr/include/security --with-ssl --with-pcre --with-lwres --with-sctp
make && make install

**Comment by gurkin33** [comment]
Hello,
And is everything ok now?

**Comment by novafiddler** [comment]
Yep. Everything is working the way I'd expect once I did the steps above

**Comment by aridhaa** [comment]
Hi
@novafiddler 

did you manage to authentication some servers with tacacsgui ? I want to use it with other than routers, is it possible ?

BR

**Comment by novafiddler** [comment]
yes... but its long, difficult, and not suitable for production use and I
do not advise it.
