### ISSUE TITLE
Проблема с паролями со спецсимволами

### ISSUE THREAD

**Issue by zirus00** [tacacsgui/tacacsgui#7]
Пароли со спецсимволами вызывают проблемы при использовании GUI
1) Пароли не проходят через хешфункцию, соотвтетственно в конфиге поле с паролем оказывается пустым
2) Пароли с некоторыми другими символами хешируются, но эти символы теряются

Очевидно проблема с экранированием спецсимволов, что вызывает проблемы при использовании сложных паролей, и является потенциальной дырой в безопасности

**Comment by gurkin33** [comment]
Добрый день! 
Проблема с экранированием дествительно есть. Подскажите, пожалуйста, о каких именно паролях идет речь. В версии 0.9.11 я пофиксил проблему с tacacs key, а так же добавил несколько фильтров при вводе пароля.

**Comment by gurkin33** [comment]
Была такая проблема. Я ввел ограничение на символы *,\,',". Добавил несколько зменений в код, в том числе, если используется DES шифрование, то пароль должен быть не больше 8 символов.

Если у вас есть пример паролей, которые могут не пройти, то прошу вас опубликовать их здесь.
