### ISSUE TITLE
unable to Assign Command_Set

### ISSUE THREAD

**Issue by tayyabtahir143** [tacacsgui/tacacsgui#70]
I am using tacacsgui version 0.9.82. everything working fine but I created a command set that I want to assign to a user so that I can restrict the user privilege. but I am unable to find the option in the user menu as well as the device menu from where I can select my command set. I have checked the documentation but new tacacsgui documentation is not available.
can anybody explain how to assign command set to a user.?
Thanks.

**Comment by gurkin33** [comment]
Hello @tayyabtahir143 ,

You should add command set to Service and then add Service to user.

Hope it helps.

**Comment by tayyabtahir143** [comment]
Hey @gurkin33 
Thanks for your response.
I am trying but there is no option to call command set in services.
I am not even able to call command set anywhere. I have checked each & every tab and option in TacacsGUI.

**Comment by tayyabtahir143** [comment]
here are screenshots of Command set and services. You can check...
[https://drive.google.com/file/d/1sVj74hviUnFvoTKgw1l-EjJB6m4dzTLD/view?usp=sharing
https://drive.google.com/file/d/1Nt1z0xjjdV00dRIt7V8S83ZejUy0Arp2/view?usp=sharing](url)

**Comment by tayyabtahir143** [comment]
you can check screenshots of Command set and Services..
https://drive.google.com/file/d/1sVj74hviUnFvoTKgw1l-EjJB6m4dzTLD/view?usp=sharing
https://drive.google.com/file/d/1Nt1z0xjjdV00dRIt7V8S83ZejUy0Arp2/view?usp=sharing

**Comment by gurkin33** [comment]
As I understood you are trying to make restrictions for Cisco device. You have to add Service Pattern, could you please click Service Patterns button and select General Cisco, where you can find field for Command sets.

Hope it helps.

**Comment by tayyabtahir143** [comment]
Type is already General (Cisco Type).

**Comment by tayyabtahir143** [comment]
ahhh you are talking about selecting General Cisco in Services. ok ok, I got this option.
it's horrible that in a long while I could not check this option.
 Bundle of thanks Buddy
Problem Solved.
