### ISSUE TITLE
user doesn't inherit group service

### ISSUE THREAD

**Issue by lediang** [tacacsgui/tacacsgui#71]
**Describe the system**
Ubuntu version: ... 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

PHP version: PHP 7.3.8
TacacsGUI API version: 0.9.77 
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: chrome

**Describe the bug**
I am not sure if this is a bug or not but i will explain my issue.
I have created a service with a command set to assign privilege 15 for Cisco devices. The service is working fine when assigned directly to the user. 
When assigning the service to a user group and trying to login with a user from this group, I am not getting the settings configured to that service (in my case privilege lev 15), but it is asking for enable password. 
The user is a local one.
Am I missing something here?

Thank you

**Comment by jasonjiangxinhui** [comment]
yes, I have a similar issue in the Junos environment.  you can do it related setting in user rather not group. it should be ok.

**Comment by lediang** [comment]
i am planning to use it with ldap for user authentication, thats why i need to configure it at group related settings

**Comment by aridhaa** [comment]
I have also this issue on juniper when I did wireshark capture during authorization the tacacsgui server does not send arguments (local-user-name, allow-commands,...), But when I put service under user it sends them and works fine
Team, please check this and try to fix it :)

**Comment by gurkin33** [comment]
Hello,

I will try to help. As I understood it works when user has the service. Could you please set this service to local user group and add test user to that group, then try and send me configuration of User Group and User.

Regards, Aleksey

**Comment by aridhaa** [comment]
Hi
Thank you for quick reply,
Yes when I put the service under the user it works fine, its like this
I have user named "ridha" who is part of "IP_Support" user-group
I created a service that allow all, here is the service configuration

"""""""""""""""""""""    
###Service Juniper START###
    **_service = junos-exec {
      set local-user-name = "ADMIN_USER"
      set allow-commands = "(all)"
      set allow-configuration = "(all)"
    } #END OF JunOS General Service
    ###Service Juniper END###_**
""""""""""""""""""""""""""
when I bind the service under the group "IP_Support" , it does'nt work, but when I bind it under the user "ridha" , who is part of group "IP_Support" it works

here is the config under the Juniper router : 

_**set system login user ADMIN_USER uid 2003
set system login user ADMIN_USER class super-user**_

I did not understand well what you mean by "set the service to local user group", you want me to test the service without tacacs, directly under the router ?

**Comment by gurkin33** [comment]
Ok. Let me ask you one more time. Could you send me configuration of User Group and User?

**Comment by gurkin33** [comment]
And as I know Juniper doesn't know "all" commands, but knows this:
set allow-commands = "(.*)"
set allow-configuration = "(.*)"

**Comment by aridhaa** [comment]
I tried that also without success
But actually the "all" works fine under the user also I have it in a production network, 
As I said when I did a packet capture these allow-commands are not sent from the tacacsgui server when I put them under the group

**Comment by aridhaa** [comment]
here is user configuration :
  _user = ridha {
    login = clear "cisco"
    member = Support_IP
    pap = login # Clone login
    enable = login # Clone login
    default service = permit
  } #END OF ridha_

and the group configuration : 

  _group = Support_IP {
    acl = IP_DEVICES
    default service = permit
    ###Service Service_Support_IP START###
    service = shell {
      set priv-lvl = 15
      default attribute = permit
      default cmd = permit
    } #END OF Cisco Router/Switch Service
    service = shell {
      set priv-lvl = 3
      default attribute = permit
      default cmd = permit
    } #END OF Huawei General Service
    service = junos-exec {
      set local-user-name = "ADMIN_USER"
      set allow-commands = "(all)"
      set allow-configuration = "(all)"
    } #END OF JunOS General Service
    ###Service Service_Support_IP END###
  } #END OF Support_IP_


In this way does'nt works

**Comment by aridhaa** [comment]
Hi Team,
I think it is a general issue, I just tried it with Fortigate and I have the same behavior : the service under the user works and under the group to which that user belongs dont work

can you help please since I dont want to repeat putting the service under each user

**Comment by gurkin33** [comment]
Could you please delete from the user group:
- acl
- all services except  JunOS General Service
and try.

**Comment by aridhaa** [comment]
user = ridha {
    login = clear "cisco"
    member = Support_IP
    pap = login # Clone login
    enable = login # Clone login
    default service = permit
  } #END OF ridha


  group = Support_IP {
    default service = permit
    ###Service Service_Support_IP START###
    service = junos-exec {
      set local-user-name = "ADMIN_USER"
      set allow-commands = "(.*)"
      set allow-configuration = "(.*)"
    } #END OF JunOS General Service
    ###Service Service_Support_IP END###
  } #END OF Support_IP


same issue , here is when I try to access config mode into juniper : 
ridha@vMX> confi
           ^
unknown command.

ridha@vMX> configure
           ^
unknown command.

ridha@vMX>

**Comment by gurkin33** [comment]
I don't know where is your problem.
My config:
  user = admin {
    login = mavis # Local Database
    member = **admin-group**
    enable = login # Clone login
  } 

  group = admin-group {
    service = junos-exec {
      set local-user-name = "admin"
      set allow-commands = "(.\*)"
      set allow-configuration = "(.\*)"
    } 
  }

When I try to login.
admin> configure 
Entering configuration mode

[edit]
admin# exit 
Exiting configuration mode

I think you can try to buy support and they will help you in remote session and give you best practice of using tacacsgui.

**Comment by aridhaa** [comment]
Thank you for your time and support, I wil try to troubleshoot further
juste one question what version you are using

**Comment by gurkin33** [comment]
The latest 0.9.82

**Comment by aridhaa** [comment]
bizzare, mine too
anyway, thanks again :)

**Comment by gurkin33** [comment]
Guys @jasonjiangxinhui and @lediang do you have any questions?

**Comment by jasonjiangxinhui** [comment]
no, thanks so much.

**Comment by lediang** [comment]
the issue is not solved. but if you say buy the support, there is nothing left to do here

**Comment by jasonjiangxinhui** [comment]
no， the issue is solved by your refer configuration. thanks so much. I tested it. it is the  Default Service Permit enables with user setting. this issue will occur.

**Comment by lediang** [comment]
> no， the issue is solved by your refer configuration

by which configuration? i haven't posted any config. 
and i have tried enabling/disabling the default service, but nothing changes

**Comment by jasonjiangxinhui** [comment]
in my environment. I disable the user's Default Service Permit setting. then it works fine. thanks gurkin33 so much

**Comment by jasonjiangxinhui** [comment]
@gurkin33 thanks so much. according to your configuration. I solved the problem.   you are so nice. It is great opensource.

**Comment by aridhaa** [comment]
Mine also is solved, I did not change any thing in the configuration, something was stucked, I just remove the user and create another one and now all is good
@jasonjiangxinhui try to remove the user and add it again

**Comment by gurkin33** [comment]
Glad to hear some guys resolve the issue. Ok. @lediang What is your issue? Could you describe?
