### ISSUE TITLE
Проблема после установки

### ISSUE THREAD

**Issue by ISQman** [tacacsgui/tacacsgui#8]
[Wed Jun 20 16:45:57.986932 2018] [:error] [pid 47548] [client 172.хх.2.хх:57994] PHP Warning:require(/opt/tacacsgui/web/api/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/tacacsgui/web/api/bootstrap/app.php on line 20

[Wed Jun 20 16:45:57.986965 2018] [:error] [pid 47548] [client 172.хх.2.хх:57994] PHP Fatal error:  require(): Failed opening required '/opt/tacacsgui/web/api/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/tacacsgui/web/api/bootstrap/app.php on line 20

файла с именем autoload.php нет.

**Comment by gurkin33** [comment]
Добрый день. 

Смогли я ответить на ваш вопрос?

**Comment by gurkin33** [comment]
Значит смог.

**Comment by taxisali** [comment]
same problem
/opt/tacacsgui/web/api/bootstrap/../vendor/autoload.php doesnt exist.
used your manual installation method.

**Comment by gurkin33** [comment]
Hello @taxisali

I specially spent an hour of my personal time, downloaded the Ubuntu 16.04 from official site, install it. Then I followed the instruction from [here](https://tacacsgui.com/documentation/system-preparation/). Just four steps. Finally I get the new copy of my project. Thank you for that experience.

For you and your friend (@ISQman ) I posted [here ](https://tacacsgui.com/documentation/install-tacacsgui/) successful output of that installation. Please take attention of every step when you install it manually. Hope it helps.

**Comment by taxisali** [comment]
Thanx for your work.
Could you do the next version with the idea, that the maschine has no internet?

**Comment by gurkin33** [comment]
You can download OVA file the main site and deploy it without internet access. Unfortunately I don't have enough time to make ISO file, but you can make it by yourself. Hope it helps.

**Comment by taxisali** [comment]
Hello again,

after upgrading your ova with your "System Reinstallation" Guide.
I get these errors again.

`[Wed Jul 18 14:59:01.386304 2018] [php7:warn] [pid 4110] [client 192.168.188.31:58562] PHP Warning:  require(/opt/tacacsgui/web/api/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/tacacsgui/web/api/bootstrap/app.php on line 20, referer: http://tacacsgui:8008/
[Wed Jul 18 14:59:01.386319 2018] [php7:error] [pid 4110] [client 192.168.188.31:58562] PHP Fatal error:  require(): Failed opening required '/opt/tacacsgui/web/api/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/tacacsgui/web/api/bootstrap/app.php on line 20, referer: http://tacacsgui:8008/`

**Comment by gurkin33** [comment]
Hello Herman,

Could you send me all output that you see when you are trying to update system? If that server does not have Internet access, please don't send me the output.
Example of output is [here](https://tacacsgui.com/documentation/install-tacacsgui/) (Successful Installation output).
My email - developer@tacacsgui.com
