### ISSUE TITLE
Automate user/device creation using external script

### ISSUE THREAD

**Issue by jcdaniel14** [tacacsgui/tacacsgui#82]
Hi, this is more of a question than an issue, I've managed to install and test tacacsgui and it works flawless.

I've noticed when I create a new user or device, the user/device is created in ***MySQL*** tables AND is also created inside ***tac_plus.cfg***

Say I want to create a new user or device via external script (Python), should I create it inside MySQL and tac_plus.cfg? 
I've used tac_plus before and I only had to create it in MySQL user/host tables, so I'm not entirely sure if tac_plus.cfg is needed for devices or local users.

**Comment by gurkin33** [comment]
Hello, 
You have to add data only to database and when you will click Test and Apply TACACSGUI will prepare tac_plis.cfg for you.
