### ISSUE TITLE
Configuration error when creating a service under usergroup

### ISSUE THREAD

**Issue by Soundchok** [tacacsgui/tacacsgui#87]
Ubuntu version: Ubuntu 18.04.5 LTS
PHP version: PHP 7.3.24-3
TacacsGUI API version: 0.9.77
Browser: Chrome

When applying a service under a usergroup i get a configuration error when trying to input:

service=fortigate {
       admin_prof=super_admin
    }

i get error  /opt/tacacsgui/tac_plus.cfg_test:58: Expected 'acl', 'default', 'double-quote-values', 'message', 'optional', 'protocol', 'return', 'script' or 'set', but got 'admin_prof' 

However this is the way (confirmed by fortinet support) that i'm supposed to set it up. So is there a way for me to force this configuration or am i missing the point?

This is for forcing an adminprofile called super_admin onto the user when logging onto my Fortigate firewall. 

Thanks for the help :) not very experienced in this.

**Comment by gurkin33** [comment]
Hello,

Could you please try to use this configuration:

service=fortigate {
set admin_prof=super_admin
}

**Comment by gurkin33** [comment]
In the new version we have special Service for FortiOS:

![image](https://user-images.githubusercontent.com/19661272/101685289-a1cd3980-3a78-11eb-86d4-7dbe00806fd2.png)

**Comment by Soundchok** [comment]
> Hello,
> 
> Could you please try to use this configuration:
> 
> service=fortigate {
> set admin_prof=super_admin
> }

Yeah that works, i mean i can do "set", but the fortigate does not recognize it due to the "set" parameter. it HAS to be just "admin_prof = super_admin"

I asked fortinet support since this is for a work production envrioment.

I will try to update the system and see what happens. will get back to you, thank you :)

**Comment by Soundchok** [comment]
Alright i've upgraded and its still the same. I can log onto the firewall but it not overwriting the admin_profile from the noaccess one i've made to super_admin

I have a debug here, i will hightlight with **BOLD** where its happens

[424] __compose_group_list_from_req-Group 'netadmin', type 1
[617] fnbamd_pop3_start-dcadminmpl
[373] radius_start-Didn't find radius servers (0)
[1031] __tac_plus_try_next_server-Try tacacs+:10.20.2.13
[358] __tac_plus_dns_cb-Resolved tacacs+:10.20.2.13 to 10.20.2.13, cur stack size:1
[278] sock_connect-connecting tacacs+:10.20.2.13: 10.20.2.13
[481] ldap_start-Didn't find ldap servers
[591] create_auth_session-Total 1 server(s) to try
[388] is_sock_connected-tcp connected
[495] build_authen_start-building authen start packet: authen_type=2(pap)
[761] tac_plus_result-Authen sending request
[403] pak_send-Encrypting pkt
[1229] fsm_tac_plus_update_result-Continue pending for req 899100333
[771] tac_plus_result-Authen receiving reply
[460] pak_recv-read all header, data len 6
[1229] fsm_tac_plus_update_result-Continue pending for req 899100333
[771] tac_plus_result-Authen receiving reply
[555] parse_authen_reply-authen result=1(pass)
[278] sock_connect-connecting tacacs+:10.20.2.13: 10.20.2.13
[1229] fsm_tac_plus_update_result-Continue pending for req 899100333
[388] is_sock_connected-tcp connected
[576] build_author_req-building author req packet: authen_type=2(pap)
[824] tac_plus_result-Author sending request
[403] pak_send-Encrypting pkt
[1229] fsm_tac_plus_update_result-Continue pending for req 899100333
[834] tac_plus_result-Author receiving reply
[460] pak_recv-read all header, data len 24
[1229] fsm_tac_plus_update_result-Continue pending for req 899100333
[834] tac_plus_result-Author receiving reply
**[704] parse_author_reply-Authorization arg0: service=fortigate** (it sees the service = fortigate, but not the auth_profile = super_admin)
[708] parse_author_reply-Authorization result=2
[788] auth_tac_plus_result-Passed group matching
[1063] find_matched_usr_grps-Group 'netadmin' passed group matching
[1064] find_matched_usr_grps-Add matched group 'netadmin'(2)
[217] fnbamd_comm_send_result-Sending result 0 (nid 0) for req 899100333, len=2012
[747] destroy_auth_session-delete session 899100333
[1040] tac_plus_destroy-tacacs+


Here is a debug of how its supposed to look

[834] tac_plus_result-Author receiving reply
**[704] parse_author_reply-Authorization arg0: service=fortigate**
**[704] parse_author_reply-Authorization arg1: admin_prof=super_admin**
[708] parse_author_reply-Authorization result=2#

**Comment by Soundchok** [comment]
And i've applied this Service to the usergroup:
![image](https://user-images.githubusercontent.com/6471596/101688285-18b00580-3a6c-11eb-8ea4-a93d389c0edf.png)

And this is the config:

![image](https://user-images.githubusercontent.com/6471596/101688389-3ed5a580-3a6c-11eb-952d-562716ae6fe3.png)

**Comment by gurkin33** [comment]
Hello,

Oh, yes it works with optional parameter. Sorry. Does it work now?

**Comment by gurkin33** [comment]
Hello,

Then I think something wrong with FortiGate configuration, in my tests it works.

**Comment by Soundchok** [comment]
Hmm.. Would you mind sharing your configuration then on your Fortigate? (The tacacs server, the usergroup and the admin user u've made) and your TacacsGui setup? because im unsure what i could have done wrong tbh.... :)

**Comment by nicklebon2** [comment]
Seeing same behaviour as the OP and have the same request. Could you share the FGT config and your Tacacsgui config?

**Comment by gurkin33** [comment]
Configuration example for Fortigate without VDOM’s:

Most of the configuration is done from CLI since some parts are not available in GUI till they are activated via CLI.

Create TACACS Profile within the VDOM:

```
config user tacacs+

    edit tacGUI

        set server 10.6.20.10 #this ip used as example

        set key TACACS_KEY

        set authen-type ascii

        set authorization enable

        set source-ip 10.6.20.1 #this ip used as example

    next

end
```

 

Create user group for TACACS Users and set TACACS Profile as member:

```
config user group

    edit tacGUI_Group

        set member tacGUI #should be the name of your TACACS Profile above

    next

end
```

 

By default FortiOS contains a super_admin group which gives user read+write access. But there is no group with only read access. Create one:

```
config system accprofile

    edit read_only

        set mntgrp read

        set admingrp read

        set updategrp read

        set authgrp read

        set sysgrp read

        set netgrp read

        set loggrp read

        set routegrp read

        set fwgrp read

        set vpngrp read

        set utmgrp read

        set wanoptgrp read

        set endpoint-control-grp read

        set wifi read

next

end
```

 

Create user to allow TACACS authentication on your Fortigate device:

```
config system admin

    edit wildcard # this can be the name of a user within your tacacs installation or a fake name.

        set remote-auth enable

        set accprofile read_only

        set vdom root # Also do this when not using VDOM’s. Root is always present.

        set wildcard enable

        set remote-group tacGUI_Group # should be the group you created earlier on

        set accprofile-override enable

    next

end
```

 

Options in wildcard user explained:

set remote-auth enable: By default the Fortigate will not allow you to logon when you configure a TACACS profile. It is mandatory to configure a user with the option “set remote-auth enable”. This will activate the TACACS+ configuration if the right “remote-group” is configured.

set accprofile: This is the profile which users will get assigned when you don’t assign a accprofile from TacacsGUI. It is highly recommended to use a accprofile with readonly rights! (Read futher for instructions how to assign accprofile from within TacacsGUI)

set wildcard enable: This option is important. If you have multiple users that will authenticate through your TACACS server you should enable this option. If you don’t enable this option, you’ll have to create an account on your FortiGate for each user with matching username to allow them to logon to your FortiGate box. Enabling this option allows you to create one user and login with all users through that account. (of course only if their password is correct which is checked within your TACACS installation)

set accprofile-override enable: Enable this option if you want to dynamically assign a accprofile from TacacsGUI (Read futher for instructions how to assign accprofile from within TacacsGUI)

--------------------------------
TACACSGUI Configuration
Add the following configuration to your group that should have all readonly rights:

```
service = fortigate

{

     optional admin_prof = "read_only"

}
```

 

Add the following configuration to your group that should have read+write rights:

```
service = fortigate

{

     optional admin_prof = "super_admin"

}
```

**Comment by nicklebon2** [comment]
Thanks for the followup, but this does not work. The accprofile defined in the group is not getting overridden. Can you show the output of the following diag?

FortiGate-60F # diag test authserver tacacs+ tacgui testuser <passwordredacted>
authenticate user 'testuser' on server 'tacgui' succeeded
Admin profile: <none>

The user is authenticated but the Fortigate does not recognize the admin profile sent from tacgui. Per Fortinet the service should not include the optional tag and  read like this:

service = fortigate
 {
admin_prof = super_admin
}


Not including the tag breaks your parser during test with the following:

27331: /opt/tacacsgui/tac_plus.cfg_test:56: Expected 'acl', 'default', 'double-quote-values', 'message', 'optional', 'protocol', 'return', 'script' or 'set', but got 'admin_prof' 27331: Detected fatal configuration error. Exiting.

**Comment by gurkin33** [comment]
Hello, Could you please send tacacs user configuration?

**Comment by gurkin33** [comment]
Here is example of my config
  user = test_1 {
    login = mavis # Local Database
    pap = login # Clone login
    ###Service fortios START###
    service = fortigate {
      optional admin_prof = admin
    } #END OF FortiOS Service
    ###Service fortios END###
  } #END OF test_1

**Comment by nicklebon2** [comment]
Doing this at the user level as you have done above appears to work. It does not work at the group level meaning the users are not inheriting group services as described in your earlier post in this thread. Users belonging to group admins defined here:

 group = admins {
    default service = permit
###MANUAL CONFIGURATION START###
service = fortigate
{
optional admin_prof = super_admin
}
###MANUAL CONFIGURATION END###
  } #END OF admins


are not getting assigned any admin_prof.

**Comment by nate-hancock-systems** [comment]
Id like to add this is an issue with palo alto networks firewalls roles as well.  For some reason, when the service is attached to the group, a user belonging to the group does not inherit the service for some reason, as mentioned by @nicklebon2.  I also confirmed that when the service is attached to the user directly, the firewall admin role is passed through to the firewall.

The question I have now is:
Is this a feature or a bug?  :D

**Comment by crapzDK** [comment]
Well yeah still have this problem with some Fortinet, any one still like to debug on this ?
