### ISSUE TITLE
Authorization log is unable to capture some commands

### ISSUE THREAD

**Issue by LamJohnn** [tacacsgui/tacacsgui#89]
**Describe the system**
Ubuntu version: ... **Ubuntu 18.04.2 LTS**
(use next command: lsb_release -a )
PHP version: ... **PHP 7.3.8-1**
(use next command: php -v )
TacacsGUI API version: **IMPORTANT** **0.9.83**
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: [e.g. chrome, safari] **Chrome**

**Describe the bug**

Authorization log is unable to capture any other Command info except "configure terminal" and "show running configuration related command". Whenever I tried to enter other command such as "show users", "telnet x.x.x.x"" the authorization log is unable to pick up any info from the catalyst Cisco Switch.

Appreciate much for your help. 

**To Reproduce**
3. See error

**Screenshots**
If you have screenshots to help explain your problem, feel free and attach them.
![Capture1](https://user-images.githubusercontent.com/77047602/103747797-27271800-503e-11eb-8030-4247c2b6409b.PNG)
**Additional context**

**Comment by gurkin33** [comment]
Hello,
It is because you have to configure aaa authorization for every privilege level. Hope it helps.

**Comment by LamJohnn** [comment]
Thanks Gurkin.  you have saved my day. :)
