### ISSUE TITLE
tacasgui dashboard takes too much time to load after login

### ISSUE THREAD

**Issue by sdiwakar123** [tacacsgui/tacacsgui#90]
HI we are using tacasgui on Ubuntu 18 and tacasgui dashboard takes too much time to load after login.

**Comment by gurkin33** [comment]
Hello,
I think it is because you have a lot of logs, there are two ways - delete old logs, make indexing.

**Comment by sdiwakar123** [comment]
thank you for reply @gurkin33 could you please guide me how to make indexing ?

**Comment by gurkin33** [comment]
You have to connect to database _tgui_ and run next queries:

```
ALTER TABLE tac_log_authentication ADD INDEX (username);
ALTER TABLE tac_log_authentication ADD INDEX (nas);
ALTER TABLE tac_log_authentication ADD INDEX (date);

ALTER TABLE tac_log_authorization ADD INDEX (username);
ALTER TABLE tac_log_authorization ADD INDEX (nas);
ALTER TABLE tac_log_authorization ADD INDEX (date);

ALTER TABLE tac_log_accounting ADD INDEX (username);
ALTER TABLE tac_log_accounting ADD INDEX (nas);
ALTER TABLE tac_log_accounting ADD INDEX (date);
```

**Comment by sdiwakar123** [comment]
do i have run above queries as it is mentioned ??

**Comment by sdiwakar123** [comment]
@gurkin33  how much time a single query can take? 
when i execute it takes long time

**Comment by gurkin33** [comment]
Hello,
It is depends on how many logs do you have. Do you have more than 10M rows in database?

**Comment by sdiwakar123** [comment]
no effect ..dashboard still slow.
one  more issue i am facing is slow authentication and timeout.

**Comment by gurkin33** [comment]
Hello,
Could you please send results of these queries for database tgui_log:
select count(*) from tac_log_authentication;
select count(*) from tac_log_authorization;
select count(*) from tac_log_accounting;

**Comment by sdiwakar123** [comment]
mysql> select count(*) from tac_log_authentication;
+----------+
| count(*) |
+----------+
| 39809735 |
+----------+
1 row in set (9.76 sec)

mysql> select count(*) from tac_log_authorization;
+----------+
| count(*) |
+----------+
|   748376 |
+----------+
1 row in set (0.15 sec)

mysql> select count(*) from tac_log_accounting;
+----------+
| count(*) |
+----------+
|    78926 |
+----------+
1 row in set (0.02 sec)

**Comment by gurkin33** [comment]
Oh, it is almost 40 millions records, huge amount. 
Do you use VM? What parameters of hardware do you use (CPU, RAM)? 
Do you use scripts which connect to devices?
How long do you use TGUI?

**Comment by sdiwakar123** [comment]
@gurkin33  
it's a VM with 8core CPU, 16GB Memory and 100 GB HDD connected on 1Gig network. 
yes we use scripts which connect to devices
We are using this VM more then 1 year.

**Comment by gurkin33** [comment]
How do you think could you delete some part of authentication logs?

**Comment by sdiwakar123** [comment]
what you recommend us should we move to hardware from VM ?
is there a way to take backup of those logs

**Comment by gurkin33** [comment]
There is no need to move to hardware, VM is more reliable solution.
You can make dump of current log database with mysqldump tool, and you will have backup, then remove part of logs.

**Comment by sdiwakar123** [comment]
@gurkin33  GUI is very slow ..is there any way to delete logs via CLI ?

**Comment by gurkin33** [comment]
@sdiwakar123 you can delete part of logs via GUI, API Settings -> Settings -> Logging -> Delete Tab

**Comment by sdiwakar123** [comment]
@gurkin33  is there any way to clear all logs from cli ?

**Comment by gurkin33** [comment]
There is the way only from mysql console.
_Delete from tac_log_authentication;_
This query will delete all authentication log.

**Comment by sdiwakar123** [comment]
@gurkin33  i am getting error when running above query 

mysql> delete from tac_log_authentication;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction

**Comment by gurkin33** [comment]
Could you please stop tac_plus service, then restart mysqld service and try again? 
systemctl stop tac_plus
systemctl restart mysql
Connect to mysql 
delete from tac_log_authentication;
systemctl start tac_plus

I think you have a mistake in a script and it takes huge amount of authentications or somebody bruteforce your devices.

**Comment by sdiwakar123** [comment]
@gurkin33  Thanks!!

Yes you are right there was some bruteforce attack, which has been sovled.
one more question.. is there a way to backup logs (example monthly basis), so that we don't face this issue again.

**Comment by gurkin33** [comment]
@sdiwakar123 You can find all logs in files separated by dates :) All logs saved and available for you in two places in database and in /var/log/tacacsgui/tac_plus/
Hope it helps.

**Comment by sdiwakar123** [comment]
@gurkin33  Once again thanks for your help!!. now we can open dashboad smoothly after deleting authentication logs.

**Comment by sdiwakar123** [comment]
@gurkin33 how can i delete some custom logs for specific ip or device? there was brutefore attack on a decivce which has generated huge logs on the Server.

**Comment by sdiwakar123** [comment]
@gurkin33 how can i delete some custom logs for specific ip or device? there was brutefore attack on a decivce which has generated huge logs on the Server.

**Comment by gurkin33** [comment]
> @sdiwakar123 you can delete part of logs via GUI, API Settings -> Settings -> Logging -> Delete Tab

Please see my message above.
