### ISSUE TITLE
Issues testing and saving the configuration when adding a new device

### ISSUE THREAD

**Issue by MatthewKahle** [tacacsgui/tacacsgui#94]
**Describe the system**
Ubuntu version: ... 
(use next command: lsb_release -a )

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

PHP version: ... 
(use next command: php -v )

php -v
PHP 7.3.26-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2021 08:00:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.26-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

TacacsGUI API version: **IMPORTANT** 
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
Browser: [e.g. chrome, safari]

php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo                                                            APIVER . "\n";'
0.9.83

**Describe the bug**

When adding a new device, I cannot save the configuration and I get an error message that the "address is already defined.
Example error message: (address deidentified) 
4147: /opt/tacacsgui/tac_plus.cfg_test:58: Host '192.168.x.x/24' already defined 4147: Detected fatal configuration error. Exiting

This error doesn't happen to the pre-existing addresses, only when new ones are added. 

**To Reproduce**
3. See error

**Screenshots**
If you have screenshots to help explain your problem, feel free and attach them.

**Additional context**

**Comment by MatthewKahle** [comment]
Actually I installed a new instance (ISO) without applying any updates, and I have the same result once I try to add a second device. The first one is added fine and passes the test, any more devices, not so much.

**Comment by gurkin33** [comment]
Hello,
Looks like you already use this address, please check configuration.
Also if you created device with ip 192.168.1.1 and try to add network like 192.168.1.0/24 you will see this error.
